### ISSUE TITLE
Přístup pro nespolupracující obce

### ISSUE THREAD

**Issue by michalskop** [cityvizor/cityvizor#107]
Mám u nás - Plasy - problém, že Rada města a většina zastupitelstva se aktivně brání zavádění transparentnosti. Menšina zastupitelstva (tj. já a pár dalších) by to ráda. Ale jelikož jsme dvojková obec, nezveřejňujeme třeba povinně smlouvy v Registru a dobrovolně to zastupitelstvo odmítlo.
Nicméně je možný si to všechno pravidelně vyžádat přes infozákon - jak smlouvy, tak třeba faktury.
Ale problém pak je, že dneska to nejde napojit na Cityvizor (a tak to dál zůstává jenom v Google sheets).

**Comment by Adel770-gl** [comment]
@michalskop jaký je aktuální stav této stále otevřené issue prosím?

**Comment by michalskop** [comment]
@Adel770-gl já myslis, že je to furt stejný

**Comment by Adel770-gl** [comment]
@evapavlik Je tohle spíše taky na debatu s product ownerem abychom věděli jakou to má prioritu?

**Comment by evapavlik** [comment]
@Adel770-gl Adelo, omlouvám se za zpoždění v reakci, přehlédla jsem tagnutí. Podle popisu se jistě jedná o vývoj nové funkčnosti, bude tedy nutné požadavek zadat do Productboardu.

Předám tuto informaci do Slacku a poté můžeme tady pro teď zavřít. Musí projít prioritizací v Productboardu. Možná už máme jiné řešení, o kterém jen nevíme.

Díky moc a krásný den.

**Comment by PavlaOM** [comment]
převedeno do ProductBoardu. Problém má dvě stránky: 1) technickou - bude nutné provedení analýzy dat, o kterým mluví@michalskop ( data v Google sheetu) a 2) filozofickou - chceme v CV zveřejňovat data obcí proti jejich vůli?

**Comment by evapavlik** [comment]
@PavlaOM Díky moc, Pavli. to vnímám, že už budeme řešit v ProductBoardu. Tady issue uzavírám.
