### ISSUE TITLE
Verzování .idea složky

### ISSUE THREAD

**Issue by Horm** [cityvizor/cityvizor#108]
Rád používám IntelliJ IDEA ne veškerý vývoj (frontend i backend). Aktuálně `.idea` složka není verzována. Repozitář obsahující sdílenou konfiguraci projektu nese určité výhody (např. Gradle projekt se automaticky synchronizuje bez počátečního nastavování atd.). 

Byl by zájem o pull request, který by tuto konfiguraci přinesl?

**Comment by evapavlik** [comment]
@martinwenisch Martine, podívej se prosím na návrh Matěje. Jelikož se jedná o technickou úpravu, nebudu zavádět do našeho Trella požadavků. Díky moc.

**Comment by martinwenisch** [comment]
@Horm Ja v tom nevidim moc vyhod, nastavovani gradle je automaticka zalezitost v Idea (ja mam teda ultimate). Navic v te slozce mam nejake specificke tooly, treba workflow pro Docker a to bych asi nechtel (1) sdilet a (2) aby mi to nekdo prepsal.

Za me ne, jestli chces probrat vyhody a nevihody muzeme rozjet diskuzi na Slacku v cityvizor channelu.
