### ISSUE TITLE
nízký limit na upload znaku obce

### ISSUE THREAD

**Issue by SmallhillCZ** [cityvizor/cityvizor#11]
_From @nesnera on October 13, 2018 18:10_

Aktuální limit je 100 KiB, ale velikost např. [SVG znaku Prahy 9](https://commons.wikimedia.org/wiki/File:Praha-09_CoA.svg) je 332 KiB (musel jsem použít PNG s 256px). Předpokládám, že u propracovanějších znaků to bude celkem běžná velikost, navrhuji tedy zvýšení.

_Copied from original issue: otevrena-data-mfcr/CityVizor#143_

**Comment by nesnera** [comment]
👍
