### ISSUE TITLE
Lepší zobrazení názvu obce

### ISSUE THREAD

**Issue by zoul** [cityvizor/cityvizor#111]
V seznamu obcí teď máme pole `nazev`, ve kterém je ale „úřední“, formální název včetně typu obce, takže třeba _Město Adamov_ místo _Adamov_. Pro běžné použití bychom chtěli ten úřední prefix odstranit a zavést jakési „display name“.

Zároveň by bylo dobré zpracovat názvy, které jsou verzálkama, takže například PEC POD SNĚŽKOU → Pec pod Sněžkou. (Ty předložky snad půjdou vyřešit pevným seznamem? Tj. všechna slova kromě známých předložek s velkým počátečním? Asi to bude i tak vyrábět nesmysly.)

PS. Aktuální datová sada v [Google Sheets](http://bit.ly/2FxDeef) pro experimenty.

**Comment by zoul** [comment]
Chvilku jsem masíroval ta data a myslím, že úřední prefixy jsou:

* obec
* městys
* město
* městský obvod
* městská část
* statutární město

**Comment by zoul** [comment]
Pokud jde o automatickou konverzi velikosti písmen, mám pár základních testů, od kterých se dá odpíchnout:

```typescript
test('Normalize city name case', () => {
    expect(normalizeTitleCase('PEC POD SNĚŽKOU')).toBe('Pec pod Sněžkou')
    expect(normalizeTitleCase('KLÁŠTEREC NAD OHŘÍ')).toBe('Klášterec nad Ohří')
    expect(normalizeTitleCase('ROKYTNICE V ORLICKÝCH HORÁCH')).toBe('Rokytnice v Orlických horách')
    expect(normalizeTitleCase('KOSTELEC NAD ČERNÝMI LESY')).toBe('Kostelec nad Černými lesy')
    expect(normalizeTitleCase('ŽĎÁR NAD SÁZAVOU')).toBe('Žďár nad Sázavou')
    expect(normalizeTitleCase('FRYŠAVA POD ŽÁKOVOU HOROU')).toBe('Fryšava pod Žákovou horou')
    expect(normalizeTitleCase('PRAHA-ÚJEZD')).toBe('Praha-Újezd')
    expect(normalizeTitleCase('BRŤOV - JENEČ')).toBe('Brťov - Jeneč')
})```

**Comment by zoul** [comment]
Práci na datech jsem migroval do https://github.com/cesko-digital/obce/issues/14, tady ale nechávám otevřeno a můžem tady vyřešit ty navazující změny.

**Comment by zoul** [comment]
Dataset už je [aktualizovaný](https://data.cesko.digital/obce/1/obce.json), přibylo pole `hezkyNazev`, možno využít.

**Comment by lukas-krecan** [comment]
Udělám to
