### ISSUE TITLE
Přidat do seznamu obcí URL instance CityVizoru, je-li

### ISSUE THREAD

**Issue by zoul** [cityvizor/cityvizor#113]
Předpokládám, že bude stačit udělat statickou mapu IČO obce → URL, kterou během zpracování dat zapracujeme do výstupu.

**Comment by martinwenisch** [comment]
Taky bych zacal statickou mapou pro testovani (obci je ted 1 v Praze a 9 v Otevrenych mestech). V pristim release by mel byt seznam mest ze vsech instanci (OM, Praha) sjednoceny pod OM (jedna z dalsich issues) a tak pujde vzit vsechny udaje z databaze.

Ale asi bych to nepridaval do datasetu (tam by nemela byt dynamicka/realtime data), ale zamergoval behem vyroby indexu pro vyhledavani.

V soucasne dobe Model je v [City.kt](https://github.com/cityvizor/cityvizor/blob/master/server-kotlin/src/city_search/City.kt) - zde je potreba zmenit mutability te url val -> var

A samotna tvorba indexu, coz je nejlepsi entry point v [CitySearchIndex](https://github.com/cityvizor/cityvizor/blob/master/server-kotlin/src/city_search/CitySearchIndex.kt)

Priklad URL:
z OM: https://cityvizor.cz/cernosice
z Prahy: https://cityvizor.praha.eu/praha1

**Comment by lukas-krecan** [comment]
Jdu se na to podívat
