### ISSUE TITLE
Zpracovani formulare zapojeni nove obce

### ISSUE THREAD

**Issue by martinwenisch** [cityvizor/cityvizor#117]
### Popis
Je potreba vytvorit endpoint pro zpracovani udaju z formulare, ktery identifikuje zajem o zapojeni nove obce do CityVizoru. Konkretne je potreba sbirat udaje (viz UI navrh):

1) email
2) jmeno
3) true/false souhlas se zasilanim informaci.

Soucasne je potreba, aby vysledky byly dostupne v realnem case, v rozumne podobe, bez technickych znalosti. (preferovana varianta je ulozeni do Google Docs).

### Technologie

Endpoint by mel byt psany v Kotlinu jako soucast server-kotlin projektu:

https://github.com/cityvizor/cityvizor/blob/master/server-kotlin/src/main/Application.kt

### Screenshot odpovidajiciho UI (FE neni soucast issue).

![obrázek](https://user-images.githubusercontent.com/55838596/72212117-9f600980-34ce-11ea-8522-cae6bd2d1381.jpeg)

**Comment by michalsvec** [comment]
Zkusim to naimplementovat.
