### ISSUE TITLE
Vysvětlit rozdíl údajů mezi cityvizorem a státní pokladnou

### ISSUE THREAD

**Issue by petrbouchal** [cityvizor/cityvizor#143]
### Zakládá se tvůj návrh na problému, který by se tím řešil? Popiš prosím daný problém.
> Není jasné, proč se celková rozpočtová čísla v cityvizoru (příklad: [Praha 2018](https://cityvizor.praha.eu/magistrat/hospodareni/vydaje;rok=2018)) často liší od rozpočtových čísel ve [státní pokladně - opět Praha 2018](https://monitor.statnipokladna.cz/ucetni-jednotka/00064581/prehled?rad=t&obdobi=1812). NB: někde (možná většinou) to sedí - viz Černošice.

### Popiš tvůj návrh řešení

> Doplnit vysvětlení do souhrnu příjmů a výdajů, so odkazem na detailnější vysvětlení v dokumentaci pro uživatele. (Vysvětlení sám neznám, předpokládám, že bude mít co do činění s konsolidacemi...)

**Comment by evapavlik** [comment]
Ahoj @petrbouchal, muzes mi prosim na sebe sdilet nejaky kontakt? Predame tento pozadavek do seznamu nasich pozadavku, ktere si evidujeme v Productboard a pokud bude nutne, radi bychom se doptali na detaily. Moc diky, Eva

**Comment by petrbouchal** [comment]
Díky za reakci. Jasně - [pbouchal] zavináč gmail.

**Comment by evapavlik** [comment]
@petrbouchal Petre, diky moc. Pro vsechny pozadavky pouzivame Productboard, tak jsem pozadavek predala tam. Dovolim si issue tady uzavrit, ok?

**Comment by petrbouchal** [comment]
Chápu, díky

**Comment by evapavlik** [comment]
Pozadavek predan do Productboardu, se zadavatelem domluveno uzavreni.
