### ISSUE TITLE
Přidat soubor security.txt

### ISSUE THREAD

**Issue by sinacek** [cityvizor/cityvizor#146]
### Zakládá se tvůj návrh na problému, který by se tím řešil? Popiš prosím daný problém.
Není jasné koho kontaktovat v případě nalezení bezpečnostní chyby

### Popiš tvůj návrh řešení

Přidat soubor `/.well-known/security.txt` s obsahem 
```
Contact: mailto:security@cesko.digital
Preferred-Languages: cs, en
Hiring: https://slack.cesko.digital/
```
a přesměrování na tento soubor z `/security.txt`

Více na https://www.michalspacek.cz/k-cemu-je-soubor-security.txt

**Comment by Adel770-gl** [comment]
@sitina - navrhované řešení je tedy aplikovatelné? Posledně jsi přidával labely, kdo by měl být assignovaný pokud je to ještě třeba?

**Comment by Adel770-gl** [comment]
@sitina máme tady nějaký progres?

**Comment by Adel770-gl** [comment]
@kafkule pokud do pondělí nebude odpověď asi je na místě řešit kdo bude pokračovat v řešení tohoto issue

**Comment by srdecny** [comment]
Tohle je hotove za par minut. Nejvic prace asi da overit, jestli ten email security@cesko.digital existuje a jestli ho nekdo bude kontrolovat. Bohuzel nevim, kdo to ma v cesko.digital na starosti -- @Adel770-gl, nevis nahodou kdo?

**Comment by evapavlik** [comment]
@srdecny Ahoj Vojto, ověříme to v našem kanále tech-leads. Pohledem na emailové účty security@cesko.digital nevidím založený.

**Comment by evapavlik** [comment]
Problém k řešení jsem vykopla v #core-team Slacku Česko.digital, odkaz: https://cesko-digital.slack.com/archives/CSXGU7F0F/p1596833908026500

**Comment by radkoa** [comment]
FYI, email `security@cesko.digital` existuje jako skupina v G Suite a doručení emailu je ověřené.

**Comment by miiila** [comment]
Soubor vytvořen: https://github.com/cityvizor/cityvizor/pull/233

@lukas-krecan Můžeš prosím pomoct s jeho zpřístupněním (na url `/.well-known/security.txt` a nastavením přesměrování ze `/security.txt`?

**Comment by miiila** [comment]
@sinacek Díky za návrh, přidal jsem tam jen pár komentářů, aby to případně mohl spravovat i někdo, kdo o tom třeba tolik neví. Zároveň chystám nějaký vysvětlující text, který bude k dispozici na wiki, takže issue ještě nezavírám.

**Comment by sorki** [comment]
Pridane globalne - https://gitlab.com/otevrenamesta/otevrenamesta-cz-configuration/-/commit/fbaf45481c497080068a722aeafda162182f8e2a

Mozte uzavriet.
