### ISSUE TITLE
Implementace lintru + vytvoření code style příručky

### ISSUE THREAD

**Issue by HonzaV** [cityvizor/cityvizor#149]
### Zakládá se tvůj návrh na problému, který by se tím řešil? Popiš prosím daný problém.
V server-kotlin je několik samostatných částí a každá z nich je většinou psána trochu jiným způsobem s trochu jinou strukturou. 

### Popiš tvůj návrh řešení

Bylo by vhodné domluvit se na jednotné struktuře, kterou by měly aplikace v server-kotlin používat, stejně jako na nějakých good habbits a ty sepsat do dokumentace pro vývojáře. Dále by bylo fajn implementovat nějaký lintr, Tomáš Pešek navrhoval https://github.com/pinterest/ktlint. Ušetří to práci vývojářům (při vymýšlení struktury při vývoji, případným úpravám kvůli nevyhovující struktuře) i tech leadovi (při vysvětlování v PR, že to vývojář musí přepsat, protože zrovna daná sturktura nám nevyhovuje).

**Comment by Adel770-gl** [comment]
@HonzaV jak to vypadá s touhle open issue? Máme nějaký závěr?

**Comment by HonzaV** [comment]
> 
> 
> @HonzaV jak to vypadá s touhle open issue? Máme nějaký závěr?

Nene, naposledy na to nebyly kapacity a přednost dostal redesign. Nevím, jestli se to od té doby nějak změnilo.

**Comment by Adel770-gl** [comment]
@SmallhillCZ nevíš náhodou zda se něco změnilo?

**Comment by SmallhillCZ** [comment]
Nevím, myslím, že ne. Pro front-end existuje [Angular Style Guide](https://angular.io/guide/styleguide). Snažili jsme se jí držet.

**Comment by SmallhillCZ** [comment]
Jo teď koukám, že se ta issues týkala pouze Kotlinu. Tak o tom vůbec nic nevím.

**Comment by Adel770-gl** [comment]
@SmallhillCZ / @HonzaV tak v tom případě mám dvě otázky: 1. Zda je to stále na pořadu dne abychom pokračovali v řešení? 2. Má některý z vás kapacitu na dokončení?

**Comment by Adel770-gl** [comment]
@SmallhillCZ / @HonzaV možná vám můj dotaz zapadl, tak se připomínám :-), viz předešlý komentář

**Comment by HonzaV** [comment]
> 
> 
> @SmallhillCZ / @HonzaV možná vám můj dotaz zapadl, tak se připomínám :-), viz předešlý komentář

1.) Já si myslím, že to cenu má.
2.) Čas na dokončení teď ale bohužel nemám a v blízký době ani mít nebudu :-/

**Comment by kafkule** [comment]
@lukas-krecan pustil ses do dokončení tohoto issue nebo se jedná jen o dílčí krok a máme někoho hledat? díky za info (cc @Adel770-gl)

**Comment by lukas-krecan** [comment]
Když se to zamerguje, tak to bude

**Comment by kafkule** [comment]
A co tomu brání?
