### ISSUE TITLE
Replace deprecated package request

### ISSUE THREAD

**Issue by SmallhillCZ** [cityvizor/cityvizor#151]
Package `request` is  deprecated since 11th of February 2020, see https://github.com/request/request/issues/3142. This affects also request-promise-native.

Used here:
 - https://github.com/cityvizor/cityvizor/blob/3f64234a6cf6e1d91567ba538610448a42a28a15/server/src/worker/tasks/download-contracts.ts
 - https://github.com/cityvizor/cityvizor/blob/3f64234a6cf6e1d91567ba538610448a42a28a15/server/src/worker/tasks/download-noticeboards.ts

**Comment by Adel770-gl** [comment]
@SmallhillCZ What is our plan for this open issue?

**Comment by SmallhillCZ** [comment]
Replace `request` package with `axios`. It is not a drop replacement, though, so you have to rewrite the actual code where request is used a little bit, but the changes should pretty minor and shouldn't require understanding of the surrounding code.

**Comment by Adel770-gl** [comment]
@SmallhillCZ so can you continue with finalization of this minor update? Or do we need somebody else for this open issue? (anybody is assignee to it)
