### ISSUE TITLE
Přidat části Prahy do JSONu pro vyhledávání

### ISSUE THREAD

**Issue by lukas-krecan** [cityvizor/cityvizor#152]
V `server-kotlin/resources/citylistmetadata_finalresult.json` chybí části Prahy takže se nedají vyhledávat.

**Comment by zoul** [comment]
Pokud si dobře pamatuju, tak v kódu pro generování datasetu už ty městské části jsou, chybí jen přegenerovat data. (Chyba byla v tom, že městské části Prahy mají jiný kód právní formy.)

**Comment by zoul** [comment]
Tohle bylo podle mě vyřešeno v #160, pokud ne, reklamujte, prosím.
