### ISSUE TITLE
Vylepšit chování enteru při vyhledání

### ISSUE THREAD

**Issue by lukas-krecan** [cityvizor/cityvizor#176]
1. Ve vyhledávácím políčku na https://cityvizor.cesko.digital napíšu Praha a stisknu enter
2. Stránka se obnoví, výsledek vyhledání se neobjeví

To by chtělo opravit

Kód sídlí zde https://github.com/cityvizor/cityvizor/tree/master/redesign

**Comment by skalahonza** [comment]
Rád bych si to vzal.

**Comment by lukas-krecan** [comment]
Jdi do toho, kdybys něco potřeboval, tak se mi ozvi na slacku

**Comment by skalahonza** [comment]
Asi by to chtělo menší redesign. Ten bug už jsem fixnul. Stačil on submit prevent. Nicméně, 
![image](https://user-images.githubusercontent.com/13693312/77250769-5e147480-6c4a-11ea-9237-1d2733df15e5.png)
Na to mscreenshotu je vidět že se cancel button překrývá s tou lupou. Mohu to předělat ať to vypadá lépe? Podle mě zbytečnost dělat na to další issue.

**Comment by lukas-krecan** [comment]
Jasně, cokoliv je zjevně špatně klidně fixni, budeme rádi.

**Comment by lukas-krecan** [comment]
Nasazeno na https://cityvizor.cesko.digital/
