### ISSUE TITLE
Formulář pro přidání obce

### ISSUE THREAD

**Issue by lukas-krecan** [cityvizor/cityvizor#177]
Ve stránce vyhledávání přidat formulář pro přidání nové obce. 

https://trello.com/c/k3n945ku/84-predelat-pridat-obec-v-searchi

API:
```
https://cityvizor.cesko.digital/api/v2/service/cityrequest
{
     "city": "Lukas test",
    "email": "test@example.org",
    "name": "Pan Starosta",
    "subscribe": true,
    "gdpr": true
}

```

Kód sídlí zde https://github.com/cityvizor/cityvizor/tree/master/redesign

**Comment by lukas-krecan** [comment]
![CV - web - jak zapojit - form vedeni obce](https://user-images.githubusercontent.com/815787/77247705-e9364000-6c33-11ea-8046-491ea7e33ac2.png)

**Comment by lukas-krecan** [comment]
![CV - web - home - form](https://user-images.githubusercontent.com/815787/77247738-239fdd00-6c34-11ea-800b-702eb975ab0c.png)

**Comment by skalahonza** [comment]
Rád bych si to vzal.

**Comment by michalsvec** [comment]
Kdyby byl problem s backendem, dej vedet. Psal jsem ho, tak to muzeme kdyztak probrat/testnout.

**Comment by ilny** [comment]
https://github.com/cityvizor/cityvizor/pull/211 🥳
