### ISSUE TITLE
Pohled přes dodavatele

### ISSUE THREAD

**Issue by SmallhillCZ** [cityvizor/cityvizor#18]
_From @janvlasaty on March 1, 2018 18:8_

Srovnávání podobně velkých obci ve stejných rozpočtových kapitolách, kdo ma jaké příjmy z najmu apod 

_Copied from original issue: otevrena-data-mfcr/CityVizor#136_

**Comment by evapavlik** [comment]
> _From @janvlasaty on March 1, 2018 18:8_
> 
> Srovnávání podobně velkých obci ve stejných rozpočtových kapitolách, kdo ma jaké příjmy z najmu apod
> 
> _Copied from original issue: [otevrena-data-mfcr/CityVizor#136](https://github.com/otevrena-data-mfcr/CityVizor/issues/136)_

Osobně si myslím, že pohled přes dodavatele by mohl být aplikovatelný i pro obec jako takovou - tzn. podívat se do výdajů přes dodavatele nezávisle na skladbě?

**Comment by evapavlik** [comment]
Je řešeno v Trello boardu: https://trello.com/c/LyHjwlAa

**Comment by evapavlik** [comment]
Je řešeno v Trello boardu: https://trello.com/c/J2P88xWg
