### ISSUE TITLE
Ukládat informace od uživatele na webu do souboru

### ISSUE THREAD

**Issue by sitina** [cityvizor/cityvizor#183]
Součástí nového webu CityVizor.cz je sběr informací od uživatele, který identifikuje zájem o zapojení jeho obce do CityVizoru.

Všechny údaje z formuláře, který uživatel odešle, je tedy nutné uložit do google doc ve formě - co formulář, to řádek.

Vyplněné údaje budou vyplněné do těchto řádků:
1, Název sloupce: Datum a čas, Vyplněná hodnota: Z formuláře ve formátu DD.MM.RRRR HH:MM
2, Název sloupce: “text ve formuláři”, Vyplněná hodnota: Z formuláře
3, Název sloupce: “text ve formuláři”, Vyplněná hodnota: Z formuláře
4, Název sloupce: “text ve formuláři”, Vyplněná hodnota: Z formuláře
5, Název sloupce: “text ve formuláři”, Vyplněná hodnota: hodnota ANO/NE
6, Název sloupce: “text ve formuláři”, Vyplněná hodnota: hodnota ANO/NE
7, Název sloupce: Lokace, Vyplněná hodnota: geolokační údaje o uživateli
8, Název sloupce: IP adresa, Vyplněná hodnota: IP adresa uživatele

Tyto údaje ukládat do definovaného Google Sheet.

![obrázek jpeg](https://user-images.githubusercontent.com/412772/77254907-26b2c180-6c64-11ea-9bd5-ce4632e9fb05.jpg)

**Comment by lukas-krecan** [comment]
Který z těch formulářů patří sem a který do https://github.com/cityvizor/cityvizor/issues/177? Mám v tom zmatek.

**Comment by michalsvec** [comment]
Ja bych to zavrel jako duplikat #177. Zda se to jako puvodni zadani toho formualre, jehoz backend jsem implementoval.
