### ISSUE TITLE
Deploy instance dev/produkce

### ISSUE THREAD

**Issue by sitina** [cityvizor/cityvizor#184]
V soucasne dobe chceme deploy instance pro 3 ruzna reseni:

- Magistrat pouziva "vse v jednom dockeru deploy"
- Otevrena mesta pouzivaji deploy na 1 VPS instanci
- Deploy do testovaci infrastruktury v public cloudu (preferovano AWS)

### Dev

Primarne je potreba nastavit projekt tak, aby se pri merge pull requestu (webhook pull_request closed + merged == true) na githubu zbuildil/otestoval (lokalni testy pro kazdy projekt + API testy pres Postman collections) a nasadil na AWS/public cloud

- Idealne bez extra infrastruktury (Jenkins ...), jde nam o jednoduche, levne reseni, eventualne potrovatelne mezi cloudy.
- Moje preference by byla AWS lambda trigger ⇒ pull na bezici instanci ⇒ build/test ⇒ restart na nejnovejsi verzi ⇒ report do email/3rd party dashboard. Tohle reseni nema zadne extra fixni naklady a zavislosti.

### Production

Urcite je potreba udrzovat zavislost na "vse v jednom dockeru", coz bych navrhoval i jako preferovany deploy pro Otevrena mesta.

**Comment by lukas-krecan** [comment]
Pro redesign deployment už mám nástřel Kubernetes deploymentu. Možná by šel použí ten https://github.com/cityvizor/cityvizor/tree/master/deployment/redesign-prod
Bylo by třeba to možná ještě obalit Helmem nebo něčím kvůli konfiguračním parametrům, ale celkem to funguje.

**Comment by SmallhillCZ** [comment]
Otevřená města běží taky v dockeru. Nevím co znamená "vše v jednom" :) Ale máme jednu instanci VPS, na ní běží docker a v něm jednotlivé image cityvizoru (server, client, backend, proxy) pouštěné jedním ručně aktualizovaným docker-compose.yml a k tomu spuštěný watchtower na automatické nasazení v případě změny docker image na docker hubu. Tam se mění automaticky při pushnutí do branch `prod`.

AFAIK máme úplně stejný deploy jako na MHMP, ale oni nemají automatický update.

**Comment by SmallhillCZ** [comment]
> Pro redesign deployment už mám nástřel Kubernetes deploymentu. Možná by šel použí ten https://github.com/cityvizor/cityvizor/tree/master/deployment/redesign-prod
> Bylo by třeba to možná ještě obalit Helmem nebo něčím kvůli konfiguračním parametrům, ale celkem to funguje.

Jaké jsou vlastně přínosy nasazení CityVizoru přes Kubernetes?

**Comment by lukas-krecan** [comment]
Přínos Kubernetes je pro mě primárně automatický deployment a hromada existujících nástrojů. Pro nasazení redesignu stačí spustit [toto](https://github.com/cityvizor/cityvizor/tree/master/deployment/redesign-prod) na čisté instanci a všechno jede včetně TLS. Automatický deployment je pak také triviální. Zadarmo pak člověk má bezvýpadkové releasy a health checky. Nevýhoda je, že se člověk musí naučit Kubernetes.

**Comment by Adel770-gl** [comment]
@lukas-krecan komu by měla být assignovaná tahle open issue? Ptám se tebe, protože jsi psal poslední komentář a není z komunikace jasné zda jste se shodli na automatické deploymentu nebo nikoliv a co je dále třeba k realizaci.

**Comment by lukas-krecan** [comment]
Dev část skoro máme. U prod části nerozumím tomu, co znamená "vse v jednom dockeru deploy". Co primárně chybí je pobavit se s potencionálními "uživateli" adminy (nebo s někým kdo ví co potřebují) a domluvit se na tom, jestli by jim skoro hotové řešení přes Helm vyhovovalo.

**Comment by Adel770-gl** [comment]
@lukas-krecan díky za odpověď. Můžu tedy tuhle open issue assignovat na tebe?

**Comment by lukas-krecan** [comment]
@Adel770-gl Můžeš, ale s největší pravděpodobností na to nebudu mít čas

**Comment by Adel770-gl** [comment]
@lukas-krecan díky moc tedy v případě že budeš vědět, že to časově opravdu nedáváš, prosím napiš tady do komentáře a s @kafkule najdeme někoho jiného

**Comment by lukas-krecan** [comment]
Časově to nedávám, hlavně tu část

> pobavit se s potencionálními "uživateli" adminy (nebo s někým kdo ví co potřebují) a domluvit se na tom, jestli by jim skoro hotové řešení přes Helm vyhovovalo.

**Comment by Adel770-gl** [comment]
@kafkule můžeš prosím zkontaktovat někoho kdo by řešil část, kterou Lukáš zmiňuje?

**Comment by kafkule** [comment]
@Adel770-gl zadala jsem do Slacku žádost ke konzultaci https://cesko-digital.slack.com/archives/CG66HNLH4/p1597225115478400

**Comment by smarek** [comment]
Přebírám zodpovědnost za tento ticket, s aktuálním návrhem procesu deploy/test u OM, bude provedeno následující

- Změna pipeline dev/test/prod, aktuální repozitář cityvizor/cityvizor bude rozdělen do více repozitářů (jednotlivých modulů
  - lokální dev bude podporován přes docker-compose
  - test a produkce budou řešeny automatickým deploy-pipeline příslušných repozitářů (master=>prod, next=>test)
- Pro jiné než OM produkce, pak bude k dispozici Docker v jednotlivých module, docker-compose v hlavním repozitáři a volitelně helm/k8s(nebo microk8s)

Stejně tak na sebe beru zodpovědnost za diskuzi s aktuálními "uživateli" (adminy), jak aktuálně nasazují a jak použitelně vidí interně stanovený plán

**Comment by smarek** [comment]
Výsledek řešení:
- Aktuální beta/prod infrastruktura je postavena analogicky k Docker-Compose (tj. jednotlivé images/containers z hub.docker.com a NGINX proxy, která je zakrývá)
- Docker Compose podporujeme jak pro deployment tak pro vývoj
- Na Helm/k8s aktuálně nemáme klientský požadavek a nemáme interní kapacity, takže tento pipeline je aktuálně nepodporován (i když stále možná funkční) a časem jej možná odstraníme z repozitáře (pro zjednodušení maintenance)
- OM prostředí v NIX bude podporováno taktéž (jak dev tak produkce) toto bude vyřešeno v #315 

Co se týče aktuálních provozů, u MHMP bude provoz převeden na Docker Compose a jinou samostatnou, produkční, instanci CV jsem s nikým neřešil.

Zpětně ještě díky @lukas-krecan za řešení Kubernetes, ale pokud se nějaký partner OM nerozhodne místo NIX/Docker používat K8s tak tento deployment model podporovat nebudeme
