### ISSUE TITLE
Import z otevřených dat klikacího rozpočtu Internet Stream

### ISSUE THREAD

**Issue by SmallhillCZ** [cityvizor/cityvizor#199]
Je potřeba implementovat automatický import z otevřených dat klikacího rozpočtu od firmy Internet Stream (viz [Černošice](http://rozpocet.mestocernosice.cz/cz/rok2020/opendata/), [Uherský brod](http://rozpocet.ub.cz/cz/rok2020/opendata/), [Nové Město na Moravě](http://rozpocet.nmnm.cz/cz/rok2020/opendata/)) do CityVizoru.

**Technologie je volitelná.** Půjde o oddělenou službu, která bude pravidelně stahovat data z klikacího rozpočtu IS a importovat je do CityVizoru pomocí standardního importního API.

**Není vyžadována účetní znalost.** Datová struktura je podobná, zdroj i výstup je CSV. Jen je potřeba data přerovnat a volitelně zagregovat. Transformace je zřejmá při nahlédnutí do [dokumentace struktury CV](https://cityvizor.github.io/cityvizor/dokumentace/) a do libovolného exportu z klikacího rozpočtu IS.

**Comment by sitina** [comment]
Abychom netříštili backend, tak by ideálně služba měla být v kotlinu.

Co se vlastní úlohy týče, je potřeba se zamyslet i nad konfigurovatelností: frekvence loadů, zdroj/cíl a logování.

**Comment by SmallhillCZ** [comment]
Frekvence je daná frekvencí zdroje. Ideálně často kontrolovat (5 min?) a ihned nahrát, když se změní. Reálně se to mění někde jednou za měsíc a někde denně.

**Comment by sitina** [comment]
@SmallhillCZ  fair enough

**Comment by lukas-krecan** [comment]
Je někde popsané, co znamenají jednotlivé typy souborů v open data formátu? Mám tu MAP.csv, RU.csv, SK.csv, SR.csv a nedokážu najít, co který soubor znamená. Jelikož nemám účetní znalost, tak se neodvažuji hádat.

**Comment by lukas-krecan** [comment]
Myslím že by pomohlo, kdyby to někdo, kdo rozumí účetnictví zanalyzoval. Stačí jen napsat, kam který soubor, sloupeček namapovat. Bojím se, že bez toho je bariéra pro programátora příliš vysoká.

**Comment by sitina** [comment]
@SmallhillCZ ^

**Comment by evapavlik** [comment]
@SmallhillCZ Martine, nemuze tu analyzu zajistit prave Martin Sebek?

**Comment by SmallhillCZ** [comment]
Určitě může. Ale tohle asi můžu sepsat i já. To původní mapování jsem dělal já, který účetnictví taky nerozumí ani trošku, tak jsem myslel, že to nebude potřeba.

MAP jsou nějaká mapová dat, nikdy jsem to nepoužil. SR je schválený rozpočet, SK je skutečné plnění, RU je upravený rozpočet. Mapping sloupců pošlu večer.

**Comment by SmallhillCZ** [comment]
Import dat probíhá ze souborů RU.csv a SK.csv, z obou shodně. Níže je tabulka z [Dokumentace](https://cityvizor.github.io/cityvizor/dokumentace/) a v pravém sloupci logika plnění (vazba na sloupec v souborech)

### Datový soubor

Název | Typ | Povinné? | Popis | Hodnota / Pole Internet Stream
-- | -- | -- | -- | --
type | text | Ano | Typ záznamu. ROZ = upravený rozpočet, KDF = došlá faktura, KOF = odešlá faktura, jiné nebo prázdné = ostatní záznamy | `DOKLAD_AGENDA`
paragraph | číslo | Ano | Rozpočtový paragraf | `PARAGRAF`
item | číslo | Ano | Rozpočtová položka | `POLOZKA`
event | číslo | Ne | Číslo akce dle číselníku | `ORGANIZACE`
unit | číslo | Ne | Číslo jednotky dle číselníku | `ORJ`
amount | částka | Ano | Částka v Kč | IF(`POLOZKA` < 5000) { `CASTKA_MD - CASTKA_DAL` } ELSE { `CASTKA_DAL - CASTKA_MD` }
date | datum ve formátu ISO 8601 (YYYY-MM-DD) | Ne | Datum, pouze u faktur | `DOKLAD_DATUM`
counterpartyId | text | Ne | IČO protistrany, pouze u faktur | `SUBJEKT_IC`
counterpartyName | text | Ne | Jméno protistrany, pouze u faktur | `SUBJEKT_NAZEV`
description | text | Ne | Popis faktury, pouze u faktur | `POZNAMKA`

### Číselník akcí

Importují se pouze unikátní srcId.

Pole | Typ | Povinné? | Popis | Hodnota / Pole Internet Stream
-- | -- | -- | -- | --
srcId | text | Ano | Číslo akce | `ORGANIZACE`
name | text | Ano | Název akce | `ORGANIZACE_NAZEV`
description | text | Ne | Popis akce, co a proč bylo nakupováno atd. | `NULL`

**Comment by michalsvec** [comment]
zacinam na tom delat

**Comment by michalsvec** [comment]
Stary kod importu: https://github.com/cityvizor/cityvizor/blob/4df66271e2e0a16a251de49551a2be825ac30fcd/server/server/import/data-sources/internet-stream.js#L174-L213

**Comment by Adel770-gl** [comment]
@david-developer-play prosímtě v jakém stavu je tahle stále open issue? Co je třeba udělat pro dokončení?

**Comment by david-developer-play** [comment]
@SmallhillCZ Už jsou známy url zdrojů a kolik jich je? @sitina Zatím jsem přidal konfigurovatelnou frekvenci loadů a zdroj.

**Comment by SmallhillCZ** [comment]
afaik jsou to tyto tři:

- http://rozpocet.ub.cz/cz/rok2020/opendata/
- http://rozpocet.mestocernosice.cz/cz/rok2020/opendata/
- http://rozpocet.nmnm.cz/cz/rok2020/opendata/

**Comment by Adel770-gl** [comment]
@david-developer-play můžeš tedy pokračovat v řešení? Nebo tě něco dalšího blokuje?

**Comment by david-developer-play** [comment]
@SmallhillCZ Na uvedených odkazech jsou .csv zazipovaná. Jsou k dispozii zdroje kde jsou data čistě v .csv. ? Jinak ještě přidám rozbalení.

**Comment by Adel770-gl** [comment]
@SmallhillCZ prosím můžeš Davidovi poskytnout zdroje dat v csv?

**Comment by michalsvec** [comment]
Ta csv je nutne stahovat periodicky a unzipovat. Je to videt i v tom nalinkovanem puvodnim kodu importu.

**Comment by david-developer-play** [comment]
@michalsvec Ok, naimplementuji i unzip. @Adel770-gl zdroje dat mam.

**Comment by PavlaOM** [comment]
@SmallhillCZ Ahoj Martine, nejsem si jista,  zda nedošlo k malému nedorozumění. @david-developer-play má za to, že pro import potřebuje jen RU.csv a Sk.csv - dovodil tak z tvé informace výše: "Import dat probíhá ze souborů RU.csv a SK.csv, z obou shodně." Ale z informace o obsahu daných souboru ( "MAP jsou nějaká mapová dat, nikdy jsem to nepoužil. SR je schválený rozpočet, SK je skutečné plnění, RU je upravený rozpočet.") plyne, že data o schváleném rozpočtu jsou v SR.csv. takže ty se musí importovat taky nebo ne? Můžeš, prosím upřesnit? Když importoval je ty dva soubory, má v CV jen faktury, zbytek je prázdný:  [https://cityvizor-test.ceskodigital.net/nmnm/faktury;rok=2020;mesic=1]. Netušíš, v čem by mohl být problém?

**Comment by SmallhillCZ** [comment]
Je to tak, RU a SK by měly stačit - v CityVizoru zobrazujeme pouze upravený rozpočet, ne schválený. Součástí SK jsou pak jak skutečné výdaje. tak se z toho vytáhnou faktury (dle příznaků KDF a KOF). @david-developer-play je někde ten kód, kterým to taháš abych se podíval, jak se to transformuje, případně si to rozběhl? To by bylo asi nejjednodušší.

**Comment by david-developer-play** [comment]
@SmallhillCZ 
Aktuální kód je vidět tady: https://github.com/cityvizor/cityvizor/commit/4ed9a95f97366d8e9ff4b2689684a56d1460ed64
Co tě asi bude zajímat:
fun fetchFile, je tam řádek `if` (ze.name == "RU.csv" || ze.name == `"SK.csv")` Pracuji pouze s těmito soubory.
fun createBudgetFromRecord, tam je parsování z polí Internet Streamu. Parsování se děje dle tvého komentáře: https://github.com/cityvizor/cityvizor/issues/199#issuecomment-647477408
`if (type == "KDF" || type == "KOF")` Pracuji pouze s došlými nebo odešlými fakturami.
fun insertIntoPayments `Payments.batchInsert`. Vše se ukláda do tabulky payments.

**Comment by smarek** [comment]
@david-developer-play ta #298 mi přijde celkem kompletní, co ještě chybí? Případně je někde vidět aktuální stav vývoje?
Už padl i návrh, že bychom se zbavili Kotlinu a funkčnost zprovoznili v aktuálním server modulu, abychom toto vyřešili ASAP, díky!

**Comment by david-developer-play** [comment]
@smarek Udělat úpravu že všechno se vkládá do tabulky Accounting a jen tam, kde `type == "KDF" || type == "KOF"` uložit do tabulky Payments.

**Comment by smarek** [comment]
Tento ticket je nyní řešen v #351, pomoc při implementaci celého konceptu konfigurovatelných periodických importů s indikací známých typů dat v TS/JS je navržena, takže pomoc v implementaci je vítána
