### ISSUE TITLE
Odkaz na zpětnou vazbu

### ISSUE THREAD

**Issue by nesnera** [cityvizor/cityvizor#207]
* vždy dostupný(?)
* běžný uživatel nebude hledat repozitář

**Comment by evapavlik** [comment]
Zadání z popisu není úplně zřejmé, poptala jsem Pavlu Kadlecovou do Slacku ohledně upřesnění. nové požadavky vkládáme do Productboardu. https://cesko-digital.slack.com/archives/CG66HNLH4/p1594844846207600

**Comment by evapavlik** [comment]
Domluveno s Pavlou Kadlecovou, že požadavek zanese do Productboardu.

**Comment by nesnera** [comment]
Míněna klasika na hlášení podnětů, chyb. Jak Google nebývá komunikativní, tak zpětnou vazbu pro gDoc má pod nápovědou, [Element/Matrix](https://matrix.org/docs/projects/client/element) pod uživatelským profilem.
Ať českou veřejnost učíme, že mohou být součástí řešení, cpal bych to přímo na titulku, zda viditelné permanentně nebo je-li OK odrolování "silný" názor nemám. Nechal bych na UXácích
Rozhodně směřovat do issue u repozitáře
Textace z Elementu:
## Report bugs & give feedback

If you run into any bugs or have feedback you'd like to share, please let us know on GitHub.

To help avoid duplicate issues, please view existing issues first (and add a +1) or create a new issue if you can't find it.
