### ISSUE TITLE
Výrazněji zobrazit datum platnosti dat

### ISSUE THREAD

**Issue by SmallhillCZ** [cityvizor/cityvizor#21]
_From @SmallhillCZ on September 25, 2017 14:14_

_Copied from original issue: otevrena-data-mfcr/CityVizor#124_

**Comment by PavlaOM** [comment]
Ahoj Martine, jaké datum platnosti dat, kde přesně by mělo být?

**Comment by SmallhillCZ** [comment]
Tohle:

![image](https://user-images.githubusercontent.com/1273865/66739733-9af56780-ee71-11e9-824e-8f75be5693c0.png)

**Comment by evapavlik** [comment]
@PavlaOM @SmallhillCZ - Ahoj, tohle je podnet od nekoho? Vzhledem k moznemu redesign bych pro ted neresila.Podle vizualu mi to neprijde jako neco k nutne zmene.

**Comment by PavlaOM** [comment]
zpětně se těžko určuje, kdo byl autorem podnětu, ale vzhledem k plánovanému redesingu to opravdu v tuto chvíli není nutné řešit

**Comment by evapavlik** [comment]
@PavlaOM @SmallhillCZ Souhlas Pavli, Martine, prosim Te, uzavri tento task. Budeme cely vizual resit v ramci redesign aplikace. Cc @martinwenisch

**Comment by evapavlik** [comment]
Uzavírám, bude řešeno v rámci redesignu aplikace, pokud bude stále požadováno.
