### ISSUE TITLE
[Redesign projekt] Nasazení zbylých informačních podstránek

### ISSUE THREAD

**Issue by ilny** [cityvizor/cityvizor#221]
@srdecny potřebuje informace
- které podstránky chybí
- doslovné znění textu

![captured (4)](https://user-images.githubusercontent.com/41956633/90662320-84b1f800-e248-11ea-9c43-a4ba998677a1.gif)

**Comment by PavlaOM** [comment]
Před chvíli jsem si to s Vojtou diskutovali telefonicky a rámcově jsme se domluvili. Detaily si budeme upřesňovat průběžně.
Když to stručně shrnu: do nového designu bude nutné zapracovat stávající podstránky https://cityvizor.github.io/cityvizor/o-aplikaci/. 
O aplikaci - dodám aktualizovaný text
Proč Cityvizor - tento text je aktuální a měl by navazovat na stručný text, který již je v podstránce nového webu Proč Cityvizor, např. pod tlačítkem Více informací o Cityvizoru.
Návody - zatím nezobrazovat - nejsou aktuální
Dokumentace - text by měl být aktuální - Vojta ověří
Data - text by měl být aktuální - Vojta ověří
Kontakt - e-mail zůstane, ale doplnila bych info o provozovateli (Otevřená města), aby bylo zřejmé na koho ten e-mail směřuje, doplnila kontakt na Č.D a přesunula zde Intro z podstránky O aplikaci - upravím a text dodám

**Comment by evapavlik** [comment]
@PavlaOM Pavlo, bavime se o menu na horni cast vedle "Proc Cityvizor"? Pokud ano, navrhuji tam nedavat tolik stranek, ale zredukovat na Proč Cityvizor, O nás, Kontakt

**Comment by PavlaOM** [comment]
Může být, jen místo " o nás " mi lépe zní "O aplikaci". A pod touto stránkou pak můžou být schované další podstránky.

Jo a úplně nám tam chybí info pro obce - "Jak zapojit obec", které je tady: https://cs.wikiversity.org/wiki/CityVizor_prakticky

**Comment by kafkule** [comment]
@srdecny Vojto, prosím, zapracuj, na čem jste se domluvili s Pavlou (viz výše) - překlopit to, co máme, následně, až budeme mít prostor, doplníme případně další texty/podstránky, pokud bude třeba, díky (cc @vojtan)

**Comment by kafkule** [comment]
@srdecny Vojto, prosím o zapracování struktury verze 1.0 v následující podobě, na počátku příštího týdne bychom měli mít k dispozici zrevidované texty od Evy Zehnálkové:

- homepage
- horní menu: Proč Cityvizor, Kontakt
- dolní menu: O aplikaci, Přihlásit se

Zároveň prosím o to, aby každá podstránka měla stejné menu, viz struktura.
Dál prosím upřesnit (vymyslet), jak zobrazovat správný počet obcí na úvodní stránce "Již 30 zapojených obcí" (nyní je statický text 30, správně má být 9, ale bude pohyblivé). - pokud je potřeba více rozpracovat, vložíme do PB
Ověřit, zda Přihlásit se bude fungovat na novém webu.

Díky! 

cc @PavlaOM

**Comment by kafkule** [comment]
@srdecny dávám do PB, prosím doplň pak svoje vstupy, díky

**Comment by srdecny** [comment]
Nasazeno (respektive resi se v issues pro redesign)
