### ISSUE TITLE
[Redesign projekt] Kliknutí na Zapojit mou obec otevře e-mailový klient.

### ISSUE THREAD

**Issue by ilny** [cityvizor/cityvizor#222]
Po kliknutí `Zapojit mou obec` na stránce `Proč CityVizor` potřebujeme, aby se
místo formuláře otevřel předvyplněný e-mailový klient.

![005381 -  Window - (2020-08-19 17 42 18)](https://user-images.githubusercontent.com/41956633/90662767-11f54c80-e249-11ea-909e-b0261211e969.png)
![005382 -  Window - (2020-08-19 17 42 27)](https://user-images.githubusercontent.com/41956633/90662768-13267980-e249-11ea-8f2e-d9d4e9ba5363.png)

**Comment by PavlaOM** [comment]
Tady bude nutné doplnit ještě nějaký text, aby uživatel nebyl překvapen, že se mu otevře jen prázdný e-mail a aby věděl, co de něj má vlastně napsat. Text dodám.

**Comment by panda7789** [comment]
@PavlaOM Tohle si vezmu, ale budu tedy potřebovat textaci prosím.

**Comment by PavlaOM** [comment]
@panda7789 posílám stručný text:
Velmi nás těší Váš zájem o Cityvizor!
Prosím, pošlete nám své jméno a kontaktní údaje (telefon, e-mail). Obratem se Vám ozveme.
Děkujeme.
