### ISSUE TITLE
Update děravých závislostí

### ISSUE THREAD

**Issue by lukas-krecan** [cityvizor/cityvizor#224]
V JS komponentách (server, client, redesign) máme komponenty s bezpečnostní dírou, je potřeba updatnout na opravené verze.

**Comment by srdecny** [comment]
Pokud to bude technicky jednoduche (nejspis nebude), bumpnout i verzi Node + Typescriptu na nejnovejsi uroven, at to mame komplet.

**Comment by smarek** [comment]
Vše co šlo bylo aktualizováno, zbývající debt je řešen v #335
Takže můžeme zavřít
