### ISSUE TITLE
synchronizace dat z pražské instance CV

### ISSUE THREAD

**Issue by evapavlik** [cityvizor/cityvizor#230]
načtení všech profilů z pražské instance <https://cityvizor.praha.eu/> do instance Otevřených měst <https://www.cityvizor.cz/>

**Comment by evapavlik** [comment]
Link to feature: https://cesko-digital.productboard.com/feature-board/planning/features/4188132

**Comment by lukas-krecan** [comment]
Vytvoreno omylem
