### ISSUE TITLE
Moznost zapamatovani hesla po prihlaseni #27

### ISSUE THREAD

**Issue by evapavlik** [cityvizor/cityvizor#236]
Když se poprvé přihlásim do Cityvizoru, chci aby se mne aplikace zeptala, zda má přihlašovací údaje trvale uložit, abych si je nemusel pamatovat a vyplňovat je při každém přihlášení.

<p></p>

Dotaz na vyvoj: Je to funkce prohlizece? Timpadem by nebylo treba vyvijet.

**Comment by evapavlik** [comment]
Link to feature: https://cesko-digital.productboard.com/feature-board/planning/features/3603434

**Comment by vojtan** [comment]
Je k dispozici dialog pro automatické ukládání hesla, ale automaticky se tento dialog nezobrazuje. Uložení hesla je možné vyvolat v browseru (testováno Chrome) kliknutím na ikonu klíče v řádku s adresou na pravé straně po přihlášení a poté heslo uložit. V tomto smyslu je možné informovat uživatele. Je chyba, že se tento dialog nezobrazí automaticky, je to pravděpodobně způsobeno tím, že přihlašování je řešeno jako dialog a ne jako zvláštní stránka. Je možné tento problém zkusit opravit pomocí tohoto návodu: https://stackoverflow.com/questions/2382329/how-can-i-get-browser-to-prompt-to-save-password
