### ISSUE TITLE
Verze pro embed

### ISSUE THREAD

**Issue by SmallhillCZ** [cityvizor/cityvizor#24]
_From @Kedrigern on July 19, 2017 21:48_

Častým využitím bude embedování strániky do webu obce.

Pro začátek by stačil nějaký parametr, který by skryl vše krom hlavního divu. A to by se jednoduše vložilo jako iframe.

_Copied from original issue: otevrena-data-mfcr/CityVizor#91_

**Comment by SmallhillCZ** [comment]
Uděláme speciální embedovací prvky, celá stránka by na embedování nebyla hezká.

**Comment by evapavlik** [comment]
Je řešeno v Trellu: https://trello.com/c/DprsYHo1
