### ISSUE TITLE
usnadnění administrace profilu

### ISSUE THREAD

**Issue by cesko-digital-tech-account** [cityvizor/cityvizor#243]
Po přihlášení se do aplikace Cityvizor a volbě "administrace" se administrátor dostane na seznam jednotlivých profilů.  Při najetí myší na příslušný řádek daný řádek zešedne, ale při pohybu po konkrétním jednom řádku se aktivně projeví prostřední sloupec - odkaz na daný profil (reálný náhled na již importovaná data ) a poslední sloupec "Akce", a to tak že se kurzor změní na "pacičku" a odkaz se podtrhne. Toto se ale neděje u prvního sloupce, který obsahuje název obce. Na první pohled není zřejmé, že pro cestu do administrace je možné kliknout na kterékoliv místo šedého řádku (kromě aktivních odkazů).

Požadavek tedy zní: je možné nějak více zvýraznit skutečnost, že celý řádek slouží jako cesta do administrace nebo název obce zaktivnit stejnýcm způsobem jako ostatní dva sloupce, tedy změnou kurzoru na "pacičku" a podržením textu?

<p></p>

![](https://productboard-files.s3.amazonaws.com/production/attachments/5bcd6152ddfe8c2a4c3ab2f991be5762ed976ab43e9fad95bc595360fabd78f4/image.png)

Komentář od Martina Kopečka: Jojo, ideálně zadat do githubu s nějakým labelem "microissue".

**Comment by cesko-digital-tech-account** [comment]
Link to feature: https://cesko-digital.productboard.com/feature-board/planning/features/4072145

**Comment by vojtan** [comment]
Změnit mouse cursor pro první sloupec s názvem města na pointer na stránce /admin/profily
