### ISSUE TITLE
Přehled změn v rozpočtu

### ISSUE THREAD

**Issue by SmallhillCZ** [cityvizor/cityvizor#25]
_From @SmallhillCZ on June 6, 2017 13:26_

- [ ] Změny v paragrafech napříč roky
- [ ] Změny v paragrafech v rámci roku - buď po částech nebo aspoň porovnání mezi schváleným a upraveným rozpočtem

_Copied from original issue: otevrena-data-mfcr/CityVizor#62_

**Comment by evapavlik** [comment]
Řešeno v Trello: https://trello.com/c/otuxbWlc

**Comment by kafkule** [comment]
Evi @evapavlik a Martine @SmallhillCZ, nemám přístup k nástěnce v Trellu, tak nevím, zda tam není zaznamenaný nějaký posun, případně prosím doplnit. Moc děkuji!

**Comment by SmallhillCZ** [comment]
Myslím, že posun v rámci cityvizoru žádný není.

Teď jsme dělali nějakou analýzu na rozpočtových datech z Monitoru státní pokladny (nejsou tam konkrétní výdaje z účetnictví) a zjistili jsme, že bez toho, abychom měli seznam konkrétních rozpočtových opatřeních nezjistíme, odkud kam se co přesouvalo. Ale dá se tam ukázat například které položky během roku rostly a které klesaly. Tj. třeba že si na pohoštění narozpočtovali milion, ale nakonec utratili tři.

Motivace je taková, že rozpočet schválený na zastupitelstvu se během roku pomalu mění rozpočtovými opatřeními, takže na konci roku tam uvidíš vždy to samé v rozpočtu i v čerpání. Tak abychom zobrazili jak dělali ty rozpočtové úpravy a jak moc se to liší od toho, co se na začátku za velké politické debaty schválilo.

**Comment by Adel770-gl** [comment]
Budeme tedy pokračovat nějak dále v řešení této open issue? @SmallhillCZ Je třeba upravit popis?

**Comment by evapavlik** [comment]
Ahoj, dohledala jsem historii a tento požadavek je nový a je přenesen v Trello, takže tady to můžeme uzavřít.
