### ISSUE TITLE
Znepristupneni administrace pro neprihlasene

### ISSUE THREAD

**Issue by cesko-digital-tech-account** [cityvizor/cityvizor#253]
Pokud vlezu na <https://cityvizor.cz/admin>, presmeruje me to na <https://cityvizor.cz/admin/profily>. Nastesti tam nejde nic delat, ale neprihlaseny uzivatel by ani toto nemel mit sanci videt.

<p></p>

V tomto případě uživatele přesměrovat na úvodní obrazovku

**Comment by cesko-digital-tech-account** [comment]
Link to feature: https://cesko-digital.productboard.com/feature-board/planning/features/5313558

**Comment by peterTylka** [comment]
hello, I would like to work on this issue, but maybe it should be part of general discussion about routing.

**Comment by vojtan** [comment]
done
