### ISSUE TITLE
Nabídnout zapamatování hesla po přihlášení

### ISSUE THREAD

**Issue by SmallhillCZ** [cityvizor/cityvizor#27]
_From @SmallhillCZ on May 21, 2017 10:49_

Chrome potřebuje pro vyvolání dialogu dvě věci:
- aby se změnila adresa
- aby na nové drese již nebyl přihlašovací formulář

_Copied from original issue: otevrena-data-mfcr/CityVizor#44_

**Comment by SmallhillCZ** [comment]
Přesměrovat rovnou na admin po přihlášení, to to vyřeší.

**Comment by evapavlik** [comment]
Je řešeno v Trello: https://trello.com/c/c9k6k9mr

**Comment by Adel770-gl** [comment]
@evapavlik v případě, že je to již řešené tady to lze uzavřít?

**Comment by SmallhillCZ** [comment]
To je něco hodně starého, asi bych to klidně uzavřel.

**Comment by evapavlik** [comment]
Ahoj, koukala jsem na proklik do Trella, tak to vyresene neni a je tam komentar, ze je to preklopene v Productboardu. Issue tedy uzavru tady, protoze pokud se tomu v Productboardu da priorita a bude se pozadovat realizace, tak se to dostane do issue.
Cc @Adel770-gl
