### ISSUE TITLE
Upravit 404 stránku

### ISSUE THREAD

**Issue by vojtan** [cityvizor/cityvizor#281]
Upravit https://cityvizor-test.ceskodigital.net/not-found podle brands manuálu zde: https://docs.google.com/document/d/1fiv0k7hgyTfR03tcpM6hJ9NrLKwQLyHtciVaYb1Gctw

použít fond podle manuálu
přidat logo cityvizor

**Comment by srdecny** [comment]
@vojtan Missing brand manual?

**Comment by peterTylka** [comment]
@vojtan Is there also image file of logo ? What about layout and texts ?

**Comment by vojtan** [comment]
@srdecny @peterTylka  Sorry, link to the document updated

**Comment by peterTylka** [comment]
@vojtan It seems that logo in wireframe is different from one in brands manual.
Maybe it would be good if designer could take a look at whole 404 page ?
