### ISSUE TITLE
Nefunkční třídění a tlačítko 'Otevřít detail akce'

### ISSUE THREAD

**Issue by vojtan** [cityvizor/cityvizor#284]
Problém 1
1. Otevři tuto stránku  https://cityvizor-test.ceskodigital.net/praha1/hospodareni/vydaje;rok=2021;skupina=31;razeni=nejvetsi
2. Klikni na tlačítko 'Abecedně'
3. Seznam zůstává setříděn podle velikosti.

Problém 2
1. Otevři tuto stránku  https://cityvizor-test.ceskodigital.net/praha1/hospodareni/vydaje;rok=2021;skupina=31;razeni=nejvetsi
2. Klikni na tlačítko 'Otevřít detail akce'
3. Nezobrazí se dialog,

**Comment by smarek** [comment]
Testováno s aktuálním master, a řazení se mění správně
