### ISSUE TITLE
Integrace vue do angular reseni nebo vice versa

### ISSUE THREAD

**Issue by cesko-digital-tech-account** [cityvizor/cityvizor#286]
Možnosti:

- Použít vue jako komponentu v angular:

<https://stackoverflow.com/questions/49724029/using-vue-components-in-angular>

<p></p>

- reverzni proxy

**Comment by cesko-digital-tech-account** [comment]
Link to subfeature: https://cesko-digital.productboard.com/feature-board/planning/features/6375888

**Comment by srdecny** [comment]
Jeste me napadlo ze by Vue a Angular bezelo v separatnich kontejnerech a routing by se resil externe pres nejakou nginx proxy nebo k8s ingress.
