### ISSUE TITLE
Kontaktní formuláře - "zapojit obec" a "máte připomínky"

### ISSUE THREAD

**Issue by cesko-digital-tech-account** [cityvizor/cityvizor#287]
Po vyplnění odešle email. 

Nutná validace vstupů.

<p></p>

Layout formulářů zde

<https://www.figma.com/file/w0IqN5Ql7I4w2GKHBRPpdW/Cityvizor>

**Comment by cesko-digital-tech-account** [comment]
Link to subfeature: https://cesko-digital.productboard.com/feature-board/planning/features/6367907

**Comment by ilny** [comment]
Podivám se na to. 😁

**Comment by ilny** [comment]
Měl jsem problém rozjet docker setup na Windows - hot reload ve Vue nefungoval.
Problém jsme prozatím vyřešili, pracovat se dá. Dále se na toto issue podívám někdy během tohoto týdne, až zas najdu čas.
