### ISSUE TITLE
Vytvoření CSS podle Figma

### ISSUE THREAD

**Issue by cesko-digital-tech-account** [cityvizor/cityvizor#290]
buttony

fonty a velikosti pro text elementy

textboxy

kolečka s čísly

podtržení textů

<p></p>

Figma link

<https://www.figma.com/file/w0IqN5Ql7I4w2GKHBRPpdW/Cityvizor?node-id=22%3A64>

**Comment by cesko-digital-tech-account** [comment]
Link to subfeature: https://cesko-digital.productboard.com/feature-board/planning/features/6367992

**Comment by srdecny** [comment]
Tohle si asi udelam v ramci vyvoje stranek.

**Comment by srdecny** [comment]
Hotovo v #306: https://github.com/cityvizor/cityvizor/blob/master/landing-page/src/assets/styles/main.scss#L48
