### ISSUE TITLE
Aktualizovat Header/Footer podle Figma

### ISSUE THREAD

**Issue by cesko-digital-tech-account** [cityvizor/cityvizor#291]
Figma link

<https://www.figma.com/file/w0IqN5Ql7I4w2GKHBRPpdW/Cityvizor?node-id=22%3A64>

**Comment by cesko-digital-tech-account** [comment]
Link to subfeature: https://cesko-digital.productboard.com/feature-board/planning/features/6367893

**Comment by srdecny** [comment]
Closed in #306
