### ISSUE TITLE
Backend pro posílání feedback do ProductBoard

### ISSUE THREAD

**Issue by cesko-digital-tech-account** [cityvizor/cityvizor#294]
Pri odeslani formulare pro  kontakt vytvorit novy insight v productboard

API <https://help.productboard.com/en/articles/4108998-notes-api-for-insights> 

<p></p>

accessToken pro pristup do productboard by nemel byt v githubu

<p></p>

**Comment by cesko-digital-tech-account** [comment]
Link to subfeature: https://cesko-digital.productboard.com/feature-board/planning/features/6367965

**Comment by srdecny** [comment]
Na co je vlastne tohle presne potreba? Pro to, aby nam lidi mohli posilat zpetnou vazbu emailem? Nestacilo by na tohle jen nejaky <mailto> odkaz? Nebo se to pouziva jeste nekde jinde?

**Comment by srdecny** [comment]
co se tyka tohoto issue https://github.com/cityvizor/cityvizor/issues/294, tak by mozna bylo implementacne (nemusel by se konfigurovat mail server) jednodussi to rovnou svihat do productboard pres API https://help.productboard.com/en/articles/4108998-notes-api-for-insights nez to posilat mailem. Ty pozadavky z webu  o zapojeni novych obci by se pak objevovaly rovnou v product board a nesly by pres email. Z meho pohledu elegantnejsi reseni

**Comment by PavlaOM** [comment]
vidím, že @srdecny byl přímo v PB rychlejší :-)
