### ISSUE TITLE
Backend pro seznam zapojených obcí

### ISSUE THREAD

**Issue by cesko-digital-tech-account** [cityvizor/cityvizor#295]

**Comment by cesko-digital-tech-account** [comment]
Link to subfeature: https://cesko-digital.productboard.com/feature-board/planning/features/6368118

**Comment by srdecny** [comment]
Po konzultaci s VN:

Uz mame endpoint v backendu: https://github.com/cityvizor/cityvizor/blob/master/server/src/routers/admin/profiles.ts

Pridat volitelny filtr na status, at se odesilaji jen viditelne profily (a zkontrolovat, jestli se tim neco nekde jinde nebreakne). 

Volitelne: Odebrat knownCities endpoint z Kotlin backend serveru.
