### ISSUE TITLE
Konfigurovatelnost header a footer polozek

### ISSUE THREAD

**Issue by cesko-digital-tech-account** [cityvizor/cityvizor#296]
Konfigurovatelnost nasledujicich polozek:

footer - provozovatel jmeno link, text

            - server poskytuje

přidat možnost schovat link o nas

přidat možnost editace stránky "o nás" v adminstraci pomocí markdown nebo html

<p></p>

<p></p>

<p></p>

**Comment by cesko-digital-tech-account** [comment]
Link to subfeature: https://cesko-digital.productboard.com/feature-board/planning/features/6381274

**Comment by srdecny** [comment]
Doplnuji pozadavek na pridani kodu s Google Analytics trackingem pro sledovani, kolik uzivatelu chodi na stranku. Nejspise se bude injectovat do hlavicky v index.html. Je potreba jak ve Vue, tak v Angularu.
