### ISSUE TITLE
Landing page by mela zobrazit cast zapojenych obci

### ISSUE THREAD

**Issue by sorki** [cityvizor/cityvizor#302]
Pri navsteve https://cityvizor.cesko.digital/ je viditelne jenom vyhledavani a neni jasne, ktere obce nastroj pouzivaji.

Uvital bych seznam obci pod vyhledavanim (napr. 10 obci serazenych podle poctu faktur).

**Comment by srdecny** [comment]
Zatim jsem si rikal ze budem zobrazovat vsechny zapojene obce (Praha jich ma 12 a Cityvizor.cz asi 9), takze se tam vejdou vsechny. Az se na hlavnim CV nastrada tech obci vic, tak bych to poresil, bud nejakym nahodnym vyberem, nastavenim jaky obce hledat v administraci, nebo zobrazovani tech obci podle uzivatele... moznosti je hodne).

**Comment by smarek** [comment]
Seznam zapojených obcí už vidím, takže imho OK, pokud ne re-open pls
https://cityvizor.cesko.digital/
