### ISSUE TITLE
Neúplná validace emailu v kontakt formuláři

### ISSUE THREAD

**Issue by vojtan** [cityvizor/cityvizor#318]
1. https://cityvizor-test.ceskodigital.net/landing/kontakt
2. Kliknout na "Chci zapojit svou obec"

test@test - je validní ačkoliv to není platná emailová adresa test@test.COM by měl být validní

ten samý problémve formuláři o nás https://cityvizor-test.ceskodigital.net/landing/o-nas

**Comment by srdecny** [comment]
Políčko pro email je přes čisté HTML jako `<input type="email">` (https://github.com/cityvizor/cityvizor/blob/master/landing-page/src/components/partials/ModalRequestCity.vue#L27), což by mělo email validovat automaticky: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email

Specifikace *validního* emailu je řekněmě... *komplikovaná*. A `test@test` je validní emailová adresa.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email#basic_validation =>

```js
⋊> ~ node                                                                  13:16:14
Welcome to Node.js v15.2.1.
Type ".help" for more information.
> /^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/.test("test@test")
true
```

Nabízí se to řešit custom regexpem, jako `/.+@.+\..+/`, ale v ten moment nebudeme akceptovat validní emaily. Je teda samozřejmě otázka, kolik lidí má email, co tímhle regexpem neprojde, ale asi bych se držel HTML standardu.

**Comment by srdecny** [comment]
(případně https://emailregex.com/ má další info o validaci emailu regexem)

**Comment by smarek** [comment]
Front-end validaci bych v tomhle případě pominul, HTML5 type=email musí stačit. Důležité je definovat na API/PB limity, tj. pokud vyžadujeme za zavináčem alespoň 2 úrovně, tak to můžeme validovat (nejen regexpem) a pak validovat chybový návratový stav z API

**Comment by vojtan** [comment]
Ok, Netušil jsem, že tímhle low prio bugem otevřeme pandořinu skříňku. Podle tohohle https://www.icann.org/news/announcement-2013-08-30-en jsou dotless jména zakázaná, takže pokud to bude jednoduše implementovatelné, navrhuju nějakou validaci na klientovi, která to bude checkovat správně. Pokud to nepůjde pořešit do hodiny, tak navrhuju to zavřít, že to funguje as designed.

**Comment by srdecny** [comment]
V #346 vyřešeno přidáním FE validace ve tvaru /.+@.+\..+/
