### ISSUE TITLE
nefunkční správa uživatelů

### ISSUE THREAD

**Issue by nesnera** [CityVizor/CityVizor#33]
Nedokáži se přepnout do správy tlačítkem "Uživatelé" z admin rozhraní.
Firefox 65.0.2 (a to jsem se připnul i do Secure mode)

**Comment by SmallhillCZ** [comment]
Už by to mělo fungovat. Já měl nějakou jinou verzi, tak jsem to měl v pořádku, ale byly tam blbě odkazy.

**Comment by nesnera** [comment]
Potvrzuji - opraveno. Díky (y)
