### ISSUE TITLE
Uherský Brod  - problém s importem dat

### ISSUE THREAD

**Issue by PavlaOM** [cityvizor/cityvizor#34]

**Comment by PavlaOM** [comment]
zdá se, že import účetních dat proběhl naposledy 19.3. a od té dob nic, i když automatický import je zapnut
https://www.cityvizor.cz/ub/admin/import-dat

**Comment by SmallhillCZ** [comment]
Měli jsme tam nějaký problém, Praha 3 vyhodila chybu a ty profily za ní se už nezaktualizovaly :/ Ale už opraveno.

**Comment by nesnera** [comment]
2019-04-14 - proběhl automatický v plánovaných 7:00. 2019-04-15 už ne (spouštěl jsem ručně v 10:16)
Navíc je tu kombinace s chybou u IS. UB má v Klikacím zveřejněná data za 2019-03 http://rozpocet.ub.cz/cz/ resp. http://rozpocet.ub.cz/opendata/opendata_2019_CSV.zip. Vnitřní soubor SK.csv však letošní data neobsahuje. Myslím, že už jsme na to IS 2x upozorňovali. Bude potřeba do komunikace zahrnout i UB (pokud se již nestalo).

**Comment by SmallhillCZ** [comment]
Podle logu se dneska ráno import spustil, ale krátce po spuštění z neznámých důvodů skončil. Žádná chyba, žádný záznam, nic. Zkoušel jsem ho teď spustit a normálně proběhl, tak nevím, kde je problém. Zkusíme, co to udělá zítra, jetli to nebyla nějaká anomálie, kdyžtak to začnu řešit.

**Comment by SmallhillCZ** [comment]
Problém nalezen a opraven.
