### ISSUE TITLE
Branches cleanup - Jsou tyto branche důležité, nebo je můžeme smazat?

### ISSUE THREAD

**Issue by smarek** [cityvizor/cityvizor#345]
Prosím jednotlivé zmíněné o informaci, zda dotyčné branche jsou ještě nezbytné, nebo zda je můžeme smazat, abychom sjednotlii aktuální dev/prod pipeline.

Cílem je mít
  - `master` - verzované release, zdroj pro hub.docker.com a další production deploy pipelines
  - `testing` - branch, ze které budeme periodicky (nebo on-commit) aktualizovat testovací prostředí
  - jednotlivé feature branches

@SmallhillCZ Martine prosím info o branchích "master-old", "master-v4", "prod" a "otevrenamesta"
přijde mi že všechny tyto můžeme smazat bez dalšího

@lukas-krecan prosím info o branchích "sequence", "Issue-199", "helm2", "helm3", "simplify-redesign", "93-redesign-cityvizor.cz" a "redesign"
kromě "Issue-199" mi přijde že jde o historické pokusy případně helm konfigurace, která je již dnes v master, případně "93-redesign", issue která byla rozdělena a dnes je řešena v landing page?

@sinacek prosím info o branchi "mhmp"
případně zda lze ty mhmp-specific úpravy nějak podporovat třeba jen úpravou deploy konfigurace nebo jinal

Pokud zmíněná branch obsahuje úpravy připravené pro merge, tak prosím PR
Pokud jde o WIP (jako třeba "feature/svg-chart-generator") pak stačí říct
Pokud jde o nějaký historický pokus oranizovat práci, tak smažeme, abychom mohli nastavit novou pipeline

Díky všem za vyjádření

**Comment by lukas-krecan** [comment]
Moje branche smazat

**Comment by sinacek** [comment]
mhmp bude vědět taky @SmallhillCZ

**Comment by SmallhillCZ** [comment]
`prod` byla větev, ze které se nasazovalo (pushem do `prod` se spustil deploy přes dockerhub), nevím jak se to teď dělá.

`mhmp` je větev, kde je současně nasazená verze na cityvizor.praha.eu

ostatní větve jsou historické.

**Comment by smarek** [comment]
Díky všem, zůstaly teda "master" (aktuální produkce ve vývoji), "mhmp" (dokud neproběhne překlopení OICT produkce na github/docker pipeline a merge praha-specific věcí) a jedna feature branch

Hotovo
