### ISSUE TITLE
Subentity-hospodareni prispevkovych organizaci #83

### ISSUE THREAD

**Issue by cesko-digital-tech-account** [cityvizor/cityvizor#393]
Vizualizovat hospodaření jednotlivých příspěvkovývch organizací zřízených danou obcí, které mají samostatné účetnictví.

<p></p>

Narocna featura, ale velmi zadana featura s priadnou hodnotou. 

<p></p>

Eminentni zajem Praha - financovani nebo vyvojar operatora ICT.

<p></p>

O podrobnější popis byl požádán pan mistostarosta Pírko z Chocně:

Myslim, ze na zacatku by stacilo, vytvorit "podrozpocet" pod mestempro jednotlive prispevkove organizace. Bez vazby mezi rozpoctem mestaa organizaci.Prispevkovky maji casto jiny ucetni program. Data musi jit importovatnezavisle. Idealne pod separatnimi ucty - kazda prispevkovka bude mitmoznost aktualizovat data jenom pro ni.Takze si to predstavuji jako stromecek:mesto - rozp. X, uzivatel A - prisp1 - rozp. Y, uzivatel B - prisp2 - rozp. Z, uzivatel C

<p></p>

Možno ladit nebo otestovat na Uherském Brodu (tajemník Vlček), který měl o tuto funcionalitu eminentní zájem. Aktuálně už svou potřebu vyřešili jiným způsobem, ale s konzultacemi souhlasil.

**Comment by cesko-digital-tech-account** [comment]
Link to feature: https://cesko-digital.productboard.com/feature-board/planning/features/3603271

**Comment by PavlaOM** [comment]
@smarek přímo v názvu už v product Boardu je zmíněné číslo issue #83, tzn. že tento požadavek by v GH už měl být, ale mezi issue s takovým číslem nic nevidím

**Comment by smarek** [comment]
> @smarek přímo v názvu už v product Boardu je zmíněné číslo issue #83, tzn. že tento požadavek by v GH už měl být, ale mezi issue s takovým číslem nic nevidím

Je tu, ale přečti si diskuzi proč je zavřený.
Zmatek mezi Trello, Github a Productboard

https://github.com/cityvizor/cityvizor/issues/83

**Comment by srdecny** [comment]
Martin Šebek martinek, pokud nemáš přístup do GH, můžeš zadání pro vývoj doplnit tady nebo poslat samostatný dokument, ale bez tebe se nehneme

Marek Sebera Martin Šebek po dohodě s Markem posouvám do GH a prosím doplnit přímo v GH.

Martin Šebek mohl jsi tady doplnit přesnější zadání, než to posuneme do GH? Marek Sebera je něco konkrétního, co je podle tebe potřeba definovat v zadání?

Martin Šebek Martine, tady máme klíčovou funkci CV. Mohl bys za sebe popsat problém, cíle, případně hrubý návrh řešení nebo cokoliv dalšího, co je podle tebe relevantní?

Pavla Kadlecová Najit nekoho odborneho na ucetnictvi majetek pro podrobnejsi popis. Zatim overit s vyvojari moznost pridani podentit a sestav. (Edited)

Nejsem si jisty, ze dokazu specifikovat jak by to melo fungovat.Myslim, ze na zacatku by stacilo, vytvorit "podrozpocet" pod mestempro jednotlive prispevkove organizace. Bez vazby mezi rozpoctem mestaa organizaci.Prispevkovky maji casto jiny ucetni program. Data musi jit importovatnezavisle. Idealne pod separatnimi ucty - kazda prispevkovka bude mitmoznost aktualizovat data jenom pro ni.Takze si to predstavuji jako stromecek:mesto - rozp. X, uzivatel A - prisp1 - rozp. Y, uzivatel B - prisp2 - rozp. Z, uzivatel C
subentity - hospodaření příspěvkových organizací

**Comment by hellcat0006** [comment]
Pro adopci současného CV (rozpočet) na CV pro ZO - účetnictví
vstupem data obsahující položky (rozdíl od současného vstupu, v závorkách nepovinný údaj, logika - puvodni-->novy):
(amountType);type;paragraph-->su;item-->su;event-->au;(unit);amount;(date);(counterpartyId);(counterpartyName);(description)

na úrovni CV - číselník su (vstup zákon), číselník au (vstup od organizace)
zobrazení příjmy - "paprsek" rozdělen dle su, jeden paprsek skupina su 50X, druhý paprsek skupina 51X,... poslední paprsek 59x
zobrazení výdaje - "paprsek" rozdělen dle su, jeden paprsek skupina su 60X, druhý paprsek skupina 61X,... poslední paprsek 69x

detail jednoho paprsku:
zobrazení "akce" - prakticky nahrazení event za au
zobrazení "položky" - prakticky nahrazení item za su

**Comment by PavlaOM** [comment]
@hellcat0006 když to tady čtu, tak nevím, zda pro to raději neudělat úplně nové issue - více srozumitelné :-)
