### ISSUE TITLE
Export dat

### ISSUE THREAD

**Issue by smarek** [cityvizor/cityvizor#394]
- [x] V API přidat funkce pro stažení dat pro účetní období, výsledkem by měly být 2 soubory CSV nebo 1 zip s obsahem
  - [x] /export/accounting/{voiliteně účetní období}
  - [x] /export/invoices/{voiliteně účetní období}
  - [x] /export/events/{voiliteně účetní období}
  - [x] /export/all/{voiliteně účetní období} -> zip s csv soubory
- [x] V administraci přidat možnost stáhnout data pro daný rok správci profilu / adminovi
- [x] Potenciálně přidat tlačítko pro stažení dat do komponenty `client`

**Comment by srdecny** [comment]
https://github.com/cityvizor/cityvizor/commit/c79e8196023f3ef747be9022e096ea30787b43c5

Stávající implementace exportů byla poměrně použitelná, tak jsem jen přidělal exportování do .zipu. V admistraci je tlačítko: 
![image](https://user-images.githubusercontent.com/7964806/112551958-3b1f2200-8dc2-11eb-97db-ca5683bcc149.png)
Do frontendu jsem tlačítko nedával, akorát by na to lidi zbytečně mačkali. Upravil jsem aspoň sekci v technické dokumentaci, kde je API zdokumentované:
![image](https://user-images.githubusercontent.com/7964806/112552000-55590000-8dc2-11eb-94cd-31fd9bd6bba0.png)
