### ISSUE TITLE
GUI pro slabozrake

### ISSUE THREAD

**Issue by cesko-digital-tech-account** [cityvizor/cityvizor#401]
cíl: Jako slabozraky obcan bych si chtela zobrazit data v citivizor . 

<p></p>

Je nutné zvážit, zda je úprava aplikace Cityvizor pro slabozraké vůbec realná vzhledem ke skutečnosti, že aplikace je založena na vizualizaci dat. Tzn. aby výsledný vizuál čitelný pro slabozraké neztratil svou vypovídací schopnost.

<p></p>

Konkrétní možné úpravy doporučuje P. Novák viz insights : Existují doporučení pro kontrast, velikost písma, možnost úparv velikosti písma, správného opatření popisky (pro čtení). Na jedné straně jsou grafy, na druhé straně jsou tabulková data a přehledy.

<p></p>

nezbytné vyjádření za vývoj - existuje nejake obecne zadani pro slabozrake? Pokud ne pojdme predefinovat. Stejne tak pokud bude prilis pracne pojdme vydefinovat co jsou dulezite prvky.

<p></p>

Neni prioritni pozadavek. Hackday kandidat.:-)

<p></p>

Udelat user research na pocet uzivatelu. Nice to have.

<p></p>

**Comment by cesko-digital-tech-account** [comment]
Link to feature: https://cesko-digital.productboard.com/feature-board/planning/features/3603183

**Comment by srdecny** [comment]
+ Accessibility obecně (kontrast)
