### ISSUE TITLE
Demo - aktualizace pro novou verzi CV

### ISSUE THREAD

**Issue by cesko-digital-tech-account** [cityvizor/cityvizor#408]
Demo Cityvizoru <https://demo.cityvizor.cz/> mělo 3 fce:

1) seznamovací - obec si mohla sama nahrát  a otestovat data vyexportovaná (nejčastěji podle našeho návodu na GINIS) z jejich účetního systému

2) bezpečnost dat - data importovaná do dema neopouštějí počítat uživatele, eliminuje se tedy riziko případného výskytu o odeslání citlivých údajů a navíc demo je dokáže také v určitých případech detekovat

3) transformační - demo umělo převést formát ručně vyexportovaných dat z GINIS ( soubory s příponou kxx) do formátu čitelného pro CV ( CSV)

<p></p>

Tato třetí fce přechodem na novou verzi CV není funkční.

<p></p>

Je nutné zvážil smysl dema a technickou náročnost obnovy této fce.

Závěr: technicky by to neměla být náročná věc a 

<p></p>

**Comment by cesko-digital-tech-account** [comment]
Link to feature: https://cesko-digital.productboard.com/feature-board/planning/features/5414954

**Comment by srdecny** [comment]
<b>Ladislav Nešněra</b>   August 11th at 9:33 AM@Pavla Kadlecová Jak na to koukám, tohle není o "Demu", kde byly hlavní cíle:• aby si lidi z obce v namlouvací fázi vlastními silami mohli v CityVizoru zobrazit svá data• která neopustí počítač/úřad (kvůli riziku úniku osobních údajů (např. jména a rodná čísla v popisech)Rozhodně jsem pro zbavování se závislostí na jednom dodavateli (pokud se stalo), nechceme "S XY na věčné časy a nikdy jinak". Je to zcela proti misi Otevřených měst.

**Comment by srdecny** [comment]
See 7f2b90c4c8ecb990f212ace202802edafa537194

Soubory z dema nyní jde opět importovat do CV. Velmi často ale datový soubor vytvořený demem je ale potřeba ještě ručně upravit (např. odstranit určité paragrafy), aby byl správný výsledek a tento postup je pro každou obec individuální.
