### ISSUE TITLE
demo neexportuje rozpočtová data

### ISSUE THREAD

**Issue by nesnera** [cityvizor/cityvizor#41]
V Demu jsou po importu z GINISu korektně vidět rozpočtová data.
Vyexportované soubory ve formátu CV v1 je však již neobsahují (parametr typ obsahuje pouze KDF a KOF, ne už ROZ).

**Comment by SmallhillCZ** [comment]
Já tam mám i ROZ. Jaký používáš zdrojový data?

**Comment by nesnera** [comment]
a opravdu se díváš do toho, co vyexportuješ z Dema jako CV v1? :thinking:

**Comment by SmallhillCZ** [comment]
Zkusil jsem opět import Gordic dat a export a následný do CityVizoru a rozpočet tam mám:
![image](https://user-images.githubusercontent.com/1273865/58172285-71f0f200-7c98-11e9-9039-814c3141abea.png)

Jaký používáš zdrojový data?

**Comment by nesnera** [comment]
- hádám, že to byla dubnová data z P7 x teď v z dema vyexportovaných CV v1 ale ROZ vidím. Prošel i ruční upload
- neprošel mi upload odkazem - visí ve stavu "Probíhá" a nejde obnovit (možná se to seklo na mém prvním pokusu, kdy jsem zadal URL vyžadující login. Sice jsem pak rozpočtový dat smazal včetně dat a založil nový, ale.. 😉
- odkaz na data předám přes Matrix

**Comment by SmallhillCZ** [comment]
Jiný importní mechanismus CV4
