### ISSUE TITLE
Vylepšení exportu a transformace dat z dema

### ISSUE THREAD

**Issue by srdecny** [cityvizor/cityvizor#414]
V aktuálním demu je potřeba udělat několik úprav (co se týče zpracování kxx Gordic dat):

- [x] Přidání sanity checků (při parsování kxx Gordic dat), jestli jsou zparsovaná data v očekáváném formátu. Pokud ne, pak fail fast a uživateli sdělit, kde je problém (která řádka není v očekávaném formátu). Cílem je zabránit tomu, že se změní struktura importovaných kxx dat dostatečně subtilním způsobem a demo bude vracet nesmysly.
- [x] Současné demo nepočítá s tím, že by v požadovaném .csv číselníku mohly být duplicitní akce. Typicky toto může nastat, pokud jsou pod dvěma různými syntetickými účty dvě akce co mají stejný ORJ, pak demo vyexportuje dvě akce se stejným ID, což je špatně. Řešením je by-default exportovat pouze akce z "hlavního" účtu 231 a uživateli nabídnout možnost, jak toto overridnout a poskytnout seznam účtů ze kterých se mají akce vyexportovat s tím, že je to na jeho triko. Asi nějaký pop-up dialog.

**Comment by smarek** [comment]
Díky, k bodu 2, vzhledem k očekávaným změnám importovaných dat, prosím přidat konfigurátor exportu z demo, teď tam bude jen možnost změnit defaultní účet (231) na jiný (výběr jen jedné možnosti z dostupných), v budoucnu bychom mohli v konfiguraci exportu řešit ještě skrytí konkrétních SÚ/AÚ/ORG/ORJ/...

**Comment by srdecny** [comment]
Hotovo, ale dost to bolelo. Konstantuji, že pokud bude potřeba nějaký větší zásah, bude daleko lepší funkcionality dema radši transplantovat do CV, aktuální stav dema opravu není udržitelný.

Zajímavé je, že regexy kterými se aktuálně parsují kxx data nepokrývají všechny možné řádky i v těch kxx souborech, které se zparsují normálně. Validuji tedy poměrně mírným regexpem a při failu vyhazuji jen alert s upozorněním, že to nemusí dopadnout dobře.
