### ISSUE TITLE
Viditelnost profilů  - oprava nastavení

### ISSUE THREAD

**Issue by PavlaOM** [cityvizor/cityvizor#430]
Správné nastavení  všech jednotlivých stavů viditelnosti:
veřejný - tam je to jasné, profil je vidět na hlavní stránce a odkaz na data je funkční
skrytý - není vidět nikde a k datům se nedá dostat ani když se zadá správná url adresa
skrytý pouze na úvodní straně - tzn. že přes úvodní stranu se nedá dohledat, ale pokud někdo zná správnou url, na data se podívat může
připravujeme  - na úvodní straně je vidět, ale název je šedý a odkaz neaktivní, po kliknutí by se měla objevit informace, že profil se připravuje

Komentář AB: Srozumitelné to je, jenom se tím zruší možnost, aby se nějaká položka zobrazila jak v roletce tak přímo na hlavní stránce. Je potřeba, aby tam taková možnost byla (přidala by se další možnost do nastavení) nebo je lepší, aby nastavení rodičovského profilu znamenalo to, že se položka nebude zobrazovat mimo roletku?

komentář  PK: 
@Antonín Beňa taková možnost nebude potřeba, buď bude obec na hlavní stránce nebo v roletě. To že to tak v tuto chvíli je, je vlastně špatně a mělo by se to spravit nasazením verze s roletami. Hlavní stránka se tak vyčistí.

**Comment by PavlaOM** [comment]
@sczuk-a a termín pro nasazení na betu do 20.12.

**Comment by PavlaOM** [comment]
@sczuk-a nastavení viditelnosti nefunguje úplně jak má, proto jsem toto issue znovu otevřela a vkládám ti tady komentáře ze slacku, abys to tam nemusel lovit:

**Comment by sczuk-a** [comment]
Černošice se zobrazují správně, protože mají nastavený rodičovský profil, ale v nastavení chybí možnost nastavení rodičovského profilu na "žádný".

**Comment by sczuk-a** [comment]
Možnost smazat rodičovský profil přidána.

**Comment by PavlaOM** [comment]
@sczuk snažila jsem se otestovat, zda pokud je profil skrytý, tak se na něj opravdu nejde dostat ani když znáš url adresu a mám nepříjemný pocit, že i když u určitého skrytého profilu byly  nahrány nějaké roky (např. plzen nebo test_vs), tak tím že jsem se ten profil snažila otevřít (kliknutím na URL - což se mi nepodařilo protože na mne vypadla hláška Stránka nenalezena) jsem tím ty nahrané roky smazala, protože už tam nejsou...můžeš to prosím prověřit?  aha tak počkej, už tam ty roky zase jsou, takže zmizely jen na chvíli... zajímavé
**no v každém případě je tam chyba a to v tom, že z administrace má být daný profil přístupný i když je skrytý, jen zvenku ne.**

**Comment by PavlaOM** [comment]
@oroztocil pokud tady něčemu z toho nerozumíš, ráda vysvětlím

**Comment by PavlaOM** [comment]
toto není nic urgentního

**Comment by oroztocil** [comment]
@PavlaOM Rozumím tomu dobře, že zbývá akorát tenhle problém?

> z administrace má být daný profil přístupný i když je skrytý, jen zvenku ne

**Comment by PavlaOM** [comment]
@oroztocil přesně tak

**Comment by oroztocil** [comment]
A přístupný z administrace znamená přístupný přes kliknutí na odkaz ve sloupci URL? Viz:

![image](https://user-images.githubusercontent.com/79744616/162826547-86df31e4-0170-4e05-9184-9150b4b8f26b.png)

**Comment by oroztocil** [comment]
Jo jo, vsimnul jsem si hned jak funguje to klikani a je to docela otravne :-). Problem je v tom, ze je akce presmerovani nastavena na element pro cely radek a odchytava klik misto standardniho vyhodnoceni kliknuti na odkaz.

Primocare reseni je omezit to presemerovani na nastaveni profilu jen na sloupec Nazev. To podle me vede na pekne chovani - do nastaveni se da dostat snadno, protoze neni nutne trefit presne text nazvu profilu (staci kliknout nekam okolo nej), ale zaroven nedochazi k neocekavanemu presmerovani, kdyz se clovek snazi kliknout na neco jineho. Je tohle reseni ok? Muzu pak nasadit na betu s ostatnimi zmenami a vyzkousis si to.

**Comment by PavlaOM** [comment]
@oroztocil souhlasím, udělej. díky.

**Comment by PavlaOM** [comment]
super, vše se zdá ok, i to kliknutí na url adresu funguje hned napoprvé. Díky. Až to bude na ostré verzi, zavřu to tady.

**Comment by oroztocil** [comment]
Ja uz jsem to issue zavrel v pull requestu. Pro priste to necham otevrene, aspon do pretestovani. (GitHub bohuzel nema pro issues jine stavy nez Open a Closed. Pro uplnejsi workflow bychom museli pouzivat bud labely anebo boardy v Projects.)

**Comment by PavlaOM** [comment]
ok, není problém. Na jiném projektu to řešíme tak, že to vývojář zavře a pak znovu otevře a po testu to pak zavřu já, ale vůbec na tom netrvám
