### ISSUE TITLE
editační formulář se otevře příliš vysoko

### ISSUE THREAD

**Issue by nesnera** [cityvizor/cityvizor#44]
V administraci kliknutím na "Vytvořit nový profil" sice vznikne, ale místo otevření pro prvotní nastavení se rovnou objeví v seznamu "Profily". Odkaz "otevřít profil" sice funguje, ale nelze v něm přejít na "Administrace" - vykopává chybovkou "OBEC NENALEZENA"

**Comment by nesnera** [comment]
Upřesnění - když neklikám na "otevřít profil", ale rovnou na řádek, lze nový nastavit (on se při založení editační formulář rovnou otevře, ale tak vysoko, že jej nevidím. Stačilo by po oznámení "PROFIL VYTVOŘEN" nezůstávat na konci obrazovky, ale dát kurzor do editačního pole.)

**Comment by SmallhillCZ** [comment]
Řeší nové admin rozhraní v CV4
