### ISSUE TITLE
Filtrování u příspěvkových organizací podle syntetiky a analytiky

### ISSUE THREAD

**Issue by oroztocil** [cityvizor/cityvizor#450]
Je potřeba doplnit filtrování záznamů v přehledech příjmů a výdajů příspěvkových organizací, aby korektně zohledňovalo kombinaci Analytického a Syntetického účtu.

**Comment by oroztocil** [comment]
Implementováno a nasazeno na betu. @PavlaOM, prosím o ověření, že to funguje, jak má.

**Comment by PavlaOM** [comment]
díky Ondro. 
@hellcat0006  můžeš potvrdit, že je to podle tvých představ?
