### ISSUE TITLE
Podpora pro Google Analytics, Matomo a další

### ISSUE THREAD

**Issue by nesnera** [cityvizor/cityvizor#48]
- [ ] V konfiguraci Client a Landing-Page nespecifikované textové pole pro JS kód, který se vloží v rámci příslušného layoutu / index.html do bloku `<script type=text/javascript></script>`

**Záměr: Tj. podporovat GA, Matomo a nebo jakoukoli jinou front-end JS analytiku, bez toho, abychom museli implementovat konkrétní trackovací kód**

Přidat Matomo (Piwik) sledování návštěvnosti
```
<!-- Matomo -->
<script type="text/javascript">
  var _paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//navstevnost.otevrenamesta.cz/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '3']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
```

**Comment by SmallhillCZ** [comment]
Není mi jasné, jaká jiná, lepší data nabízí oproti stávajícím Google Analytics

**Comment by evapavlik** [comment]
Navrhuji ponechat stavajici Google Analytics. Az narazime na jejich limity, muzeme uvazovat o zmene. GA je nerozsirenejsi a muzeme vyuzit nejvice specialistu. @nesnera, @SmallhillCZ Martine, uzavri prosim pro ted.

**Comment by nesnera** [comment]
Důvod pro přechod (či pro ověření klidně paralelní běh) není technický/funkční, ale strategicko etický. "Mono" něco (kultury, poly) jsou systémově špatně a není-li to nutné, proč je podporovat a navíc cpát data soukromé firmě? Je to také v rozporu s cíli spolku obce emancipovat na "dodavatelích".
Nakolik gA specialisty reálně využíváme bych nechal na jinou komunikaci.
Provedení je otázkou pár minut

Osvětově:
- docela to řešili Piráti ([ucelenější pohled](https://forum.pirati.cz/post520793.html#p520793), drbka [k daním](https://forum.pirati.cz/viewtopic.php?f=822&t=37734&start=30#p521064) a co vlastně od sledování stránek [sami očekávají](https://forum.pirati.cz/viewtopic.php?f=822&t=37734&start=100#p525574))
- připomenutí ICT [monopolů/hegemonů](https://zahranicni.ihned.cz/c1-66204960-mladi-muzi-s-pilou-proc-nastal-cas-pristrihnout-kridla-technologickym-firmam)
- a když padne kosa na kámen [v ICT v našem kontextu](https://www.lupa.cz/clanky/thea-zinner-evisions-seo-experti-museji-porad-hlavne-skakat-jak-google-piska/) nebo třeba [knihovnictví](http://www.spir.cz/proc-se-bojime-googlu)
