### ISSUE TITLE
Přepínátko pro zobrazování 8-čkových položek (OM)

### ISSUE THREAD

**Issue by PavlaOM** [cityvizor/cityvizor#481]
Tvorba možnosti přepnout mezi variantami pro zobrazování 8-čkových položek.

Cíl: umožnit obcím volbu zobrazení osmičkových položek, které souvisí s financováním.

Info od MŠ: zrovna na první dobrou je tohle u Ostravy problém min. v rozpočtu. Samozřejmě to pak zobrazuje bez financování a to je pak „nevyrovnaný“ rozpočet (tzn. v administraci „zobraz/nezobraz“).

**Comment by oroztocil** [comment]
Přidal jsem nové nastavení do profilů, kteréú umožňuje vybrat způsob výpočtu ročních součtů.

![image](https://user-images.githubusercontent.com/79744616/173182028-9322f5e5-6f6d-4468-8d26-e9ac73a8e8b0.png)

Mám dvě otázky:

1. Vyhovují vám použité textové popisky (viz obrázek)? Navrhněte případně jiné.
2. Jaká možnost má být zvolena pro existující a nové profily defaultně na začátku? V tuhle chvíli se všem profilům ze začátku nastavuje varianta "Kompletní" (tzn. že starší způsob výpočtu, který zahrnuje všechny položky, potenciálně i ty nezobrazované v aplikaci).

**Comment by PavlaOM** [comment]
Ondro, vypadá to fajn.
ad1) textové popisky jsou ok
ad2) souhlas, přednastavený ať zůstane zatím starší způsob.
Až to ale nasadíš na ostrou verzi, bude nutné to hned změnit Karlovarskému kraji, aby to měl tím novým způsobem, můžeš to pak hned udělat?

Nejsem si ovšem vůbec jista, zda návrat k původnímu zobrazení vyřeší Ostravě aktuální problém s nesrovnalostmi ve výdajích.
![image](https://user-images.githubusercontent.com/48987369/179533610-ac16cb4f-9ebc-4c63-a339-a9c3394c59d6.png)

Tvrdí, že předtím byly výdaje v pořádku.
Mi to ale mnohem více připomíná problém karlovarského kraje s chybějícím záznamem v číselníku.

**Comment by oroztocil** [comment]
Nasadil jsem úpravu na ostrou verzi spolu s opravou https://github.com/cityvizor/cityvizor/issues/493 a zobrazované součty nyní sedí.

![image](https://user-images.githubusercontent.com/79744616/179624671-45f30bec-8928-4847-966b-212ff768d77d.png)

**Comment by PavlaOM** [comment]
@oroztocil super, díky.
