### ISSUE TITLE
Úprava vizualizace příspěvkovek (OM/OICT)

### ISSUE THREAD

**Issue by PavlaOM** [cityvizor/cityvizor#485]
Cílem je, aby příspěvkovky nebyly zobrazeny jako nekonečný seznam, ale aby je bylo možné rozdělit do podsekcí jako např, podle oblastí (sociální, kulturní apod.) podle volby dané obce nebo kraje.
Ondro, udělej do testovací verze nějaký návrh, jak uznáš sám za vhodné, že by to mělo vypadat.

**Comment by oroztocil** [comment]
Udělám na ty kategorie dropdown v Administraci a poladím nastavování rodičovského profilu.

**Comment by oroztocil** [comment]
Upraveno
