### ISSUE TITLE
Bug – nemožnost odstranit profil příspěvkovky

### ISSUE THREAD

**Issue by PavlaOM** [cityvizor/cityvizor#487]
Bug – nemožnost odstranit profil příspěvkovky

![image](https://user-images.githubusercontent.com/48987369/173068408-49a67bab-87a1-46e7-952b-5912e05f9b41.png)

![image](https://user-images.githubusercontent.com/48987369/173068498-abdad390-ac99-45e2-91dd-747bd578a035.png)
 i po potvrzení SMAZAT se nic nestane

**Comment by oroztocil** [comment]
Opraveno v release 5.6.0
