### ISSUE TITLE
Úprava nadpisů pro kraje

### ISSUE THREAD

**Issue by oroztocil** [cityvizor/cityvizor#499]
Je potřeba upravit názvy dvou pojmů v záložce Přehledy, tak aby tyto pojmy byly univerzální i pro kraje:

1. text „Přehled výdajů obce“ nahradit textem „Přehled výdajů“
2. text „Bydlení“ nahradit textem „Územní rozvoj“, příslušný oddíl paragraf má název „Bydlení, komunální služby a územní rozvoj“.

**Comment by oroztocil** [comment]
Upravil jsem a nasadil

![image](https://user-images.githubusercontent.com/79744616/180625113-83302433-96e7-4903-b421-d370838529c2.png)

(Vpravo nový stav)

**Comment by PavlaOM** [comment]
@oroztocil díky
