### ISSUE TITLE
Přidání filtrů profilů do administrace + vyhledávání

### ISSUE THREAD

**Issue by PavlaOM** [cityvizor/cityvizor#506]
Aktuálně je v administraci seznam úplně všech profilů [https://www.cityvizor.cz/admin/profily], obce dohromady s příspěvkovkami.

Cílem je:

1. snadno vyhledávat, pokud někdo hledá konkrétní obec nebo organizaci
2. smysluplné přehledy, např. seznam všech obcí nebo příspěvkovky konkrétní obce

Řešení: prostřednicvím nastavení filtrů a pole pro vyhledávání ? (nebo řádek kde se začne psát název a odpovídající obce nebo organizace se nabídnou?)

**Comment by PavlaOM** [comment]
@oroztocil Mohl by jsi navrhnout nějaké konkrétní řešení Ondro?

**Comment by oroztocil** [comment]
Ahoj, vyměnil bych stávající "hloupou" tabulku za nějakou existující Angular komponentu pro "chytré tabulky" (s filtrováním, řazením, stránkováním). Z jiného projektu mám docela dobrou zkušenost s https://www.primefaces.org/primeng/table/filter. Implementace pro náš use case by měla být velice rychlá. Knihovna má otevřenou licenci (MIT).

**Comment by oroztocil** [comment]
Nahodil bych to a dal k vyzkoušení na betě, ano? UX detaily pak můžeme snáz doladit, než když to budeme designovat dopředu na papíře 🙂

**Comment by PavlaOM** [comment]
Super, díky!

**Comment by oroztocil** [comment]
Implemntováno a nasazeno na betu. Podívej se na to prosím a dej vědět 🙂

**Comment by PavlaOM** [comment]
Díky, Ondro. Cíl číslo 1.  (snadno vyhledávat, pokud někdo hledá konkrétní obec nebo organizaci) máme vyřešen.

**Comment by PavlaOM** [comment]
Napadá tě, jak zajisti dosažení cíle č. 2 ?: smysluplné přehledy, např. seznam všech obcí nebo příspěvkovky konkrétní obce.
Např. mne zajímá Ostrava a všechny její městské části. Aktuálně si musím otevřít další okno, abych věděla, jaké městské části pod Ostravu patří a pak si je jednotlivě najít v administraci, pokud se potřebuji např. podívat jaké mají nastavení.
Byl by možný pohled na celý "strom" i v administraci? Abych viděla vše co je pod hlavní Ostravou?

U ostravy se to aktuálně dá vyřešit tak, že se použije filtr na URL, protože se zdá, že všechny obvody mají slovo ostrava v URL, ale u přípěvkovek to tak není.

Rozumíš mi, o co mi jde?

**Comment by oroztocil** [comment]
@PavlaOM Rozumím ti, zkusím to implementovat s rozbalovacím stromem v rámci tabulky. Hlavní řádek v tabulce pro rodičovský profil a půjde u něj rozbalit "vnořené" řádky s podřazenými profily.

Alternativně můžu přidat další filtrovatelný sloupec pro "Rodičovský profil" a přidat do řádek s rodičovským profilem tlačítko, kterým půjde snadno vyplnit do daného filtru hodnotu, která způsobí vyfiltrování odpovídajících profilů. (Možná to zní komplikovaně, ale v praxi to bude snad intuitivní.)

Taky můžeme (zároveň) přidat seznam podřazených profilů do detailu rodičovského profilu, s prokliky na jejich detaily.

**Comment by oroztocil** [comment]
Druhy pozadavek vyresen v #590
