### ISSUE TITLE
Integrace služby pro statistiky návštěvnosti

### ISSUE THREAD

**Issue by oroztocil** [cityvizor/cityvizor#574]
Aplikace aktuálně nijak nepočítá návštěvnost. Je potřeba integrovat vhodné řešení pro získání alespoň základních statistik.

Nabízí se použít Matomo v režimu bez cookies, protože nevyžaduje (z hlediska GDPR) potvrzovací tlačítko, které by znamenalo zhoršení UX.

Viz https://matomo.org/faq/new-to-piwik/how-do-i-use-matomo-analytics-without-consent-or-cookie-banner/

**Comment by PavlaOM** [comment]
@oroztocil @prusovak2 kdy by to prosím mohlo být hotové?

**Comment by oroztocil** [comment]
Po krátké analýze možností jsme zvolili řešení Plausible. Je nasazené na [https://navstevnost.otevrenamesta.cz](https://navstevnost.otevrenamesta.cz). Další informace viz Slack.
