### ISSUE TITLE
Sekce na hlavní stránce LandingPage

### ISSUE THREAD

**Issue by prusovak2** [cityvizor/cityvizor#577]
Aktuálně je na [hlavní stránce landing page ](https://cityvizor.cz/landing) zobrazena jedna sekce pevně pojmenovaná `zapojené obce`, ve které jsou zobrazeny všechny profily, co nemají rodičovský profil. Pro Pražskou instanci Cityvizoru to není dostatečné. 

Je třeba nově přidat koncept sekcí. Každá sekce bude mít jméno (konfigurovatelné v databázi) a pořadí, ve kterém má být robrazena na main page. Profily, které mají být v dané sekci zobrazeny, se na danou sekci budou odkazovat přes její id. Nově tedz budou na main page zobrazeny profily, co mají nastavené id sekce (namísto profilů, které nemají nastaveného rodiče).
Díky tomu bude možné pro jednotlivé instance Citzvizoru nastavit, jaké sekce mají být zobrazenz na main page a jaké profily do nich mají patřit. 
Profil, který má nastavné jak id sekce, tak id rodičovského profilu, bude robrazen jak na main page, tak na ProfileSelectionPage svého rodičovského profilu.
V rámci sekcí budou profily zobrazovány v abacedním pořadí.

### Implementacni zadani
*  pridat novou tabulku `section(id, name_cs, name_eng, order)`
*  pridat do tabulky `profiles`  nullable sloupec `sectionId`
*  vytvorit rest api pro selection
*  upravit main page, aby zobrazovala selections
*  upravit existujici produkcni data tak, aby na main page byly robrazeny ty same profily jako pred provedenim zmeny
*  pridat do administrace dropdown pro prirazeni profilu do sekce
*  odstranit z moznosti pro status profilu moznost `preview` (`skryty na uvodu`), ktery je nyni redundatni vuci nenastavenemu sectionId, upravit existujici data tak, aby `preview` profily mely status `pending` a sectionId null, upravit zobrazovani profilu v administraci, aby bylo patrne, ze dany profil ma sectionId i parentId null a neni tedy zobrazen ani na main page ani na ProfileSelectionPage zadneho profilu

**Comment by oroztocil** [comment]
Implementovano v release 5.5.0
