### ISSUE TITLE
Pridat sloupec `Zrizovatel` do tabulky na ProfileSelectionPage

### ISSUE THREAD

**Issue by prusovak2** [cityvizor/cityvizor#578]
Do tabulky na ProfileSelectionPage je třeba přidat sloupec `Zrizovatel`, ktery bude obsahovat jmeno nadrazeneho profilu daneho profilu. Podle sloupce bude mozne filtrovat (dropdown). 

V administraci je treba upravit logiku nastavovani nadrazene profilu pro dany profil, tak aby podporovala a zaroven validovala nasledujici dve moznosti hierarchii rodic-potomek.

![image](https://github.com/cityvizor/cityvizor/assets/79744616/de7bbc51-4bab-4ed5-a93f-e296b39b47da)

Je potreba upravit, jak se posilaji data z BE na ProfileSelectionPage

**Comment by oroztocil** [comment]
Implementovano a nasazeno.
