### ISSUE TITLE
Administrace - hromadné přidělení správy příspěvkovek

### ISSUE THREAD

**Issue by PavlaOM** [cityvizor/cityvizor#585]
Potřebuji rozšířit kompetence správců profilů např.  pro p. Tomáše Zmudu a přiřadit mu kromě správy profilu Středočeského kraje také profily všech příspěvkových organizací.
Aktuálně nejsem schopna poznat, které příspěvkovky spadají pod Středočeský kraj (usuzuji, že to tedy budou asi všechny profily, které nemají v názvu uvedeno nějakou obec).

Potřebuji tedy:
A) buď nějakým způsobem v přehledu profilů viz obrázek identifikovat příspěvkovky daného kraje. Následně je mohu jednu po druhé přiřadit do správy pana Zmudy.

B)Nebo je na tomto seznamu nahradit jediným řádkem Příspěvkové organizace Středočeského kraje.

C) Nebo automaticky přiřadit osobě, která dostane oprávnění k nějakému profilu také admin práva k jejich městským částem, obvodům a příspěvkovkám.

![image](https://github.com/cityvizor/cityvizor/assets/48987369/b7da32c0-d21b-4406-8900-d1df6ee5f54b)

ideální by asi bylo řečení C, pokud by to bylo příliš složití, tak řešení B a v nouzi bych se dočasně spokojila i s řešením A.

**Comment by oroztocil** [comment]
Ahoj, navrhuju s drobnou zmenou variantu C: do menu na obrazku k radku s profilem, ktery uz ma dany uzivatel dany do spravy a zaroven ten profil ma nejake podprofily (na obrazuku Stredocesky kraj) pridat tlacitko "Pridat vsechny podprofily" (popisek pripadne navrhni jiny).

To ze se musi upravit Administrace tak, aby bylo snadno videt vsechny podprofily pod nejaky profilem, to je taky pravda, ale to muzeme vyresit pak separatne.

**Comment by PavlaOM** [comment]
prosím také i info, kdy na to budete mít prostor

**Comment by oroztocil** [comment]
Implementováno.

**Comment by PavlaOM** [comment]
Super, díky. Nasadíš to prosím i na testovací verzi a dáš vědět OICT?

**Comment by oroztocil** [comment]
Na betě to nasazené je. OICT můžu pak napsat, ale myslím, že mají notifikace na GitHub releasy.

**Comment by PavlaOM** [comment]
aha, tak mi se asi načetla ještě nějaká starší verze z prohlížeče, protože betu jsem měla stále ještě s roletou, ale už je to také ok. Díky. Notifikace pro OICT určitě stačí.

**Comment by PavlaOM** [comment]
toto issue tedy zavřu a vytvořím nové na " To ze se musi upravit Administrace tak, aby bylo snadno videt vsechny podprofily pod nejaky profilem, to je taky pravda, ale to muzeme vyresit pak separatne." ok?

**Comment by oroztocil** [comment]
> aha, tak mi se asi načetla ještě nějaká starší verze z prohlížeče

Jo změny na webovce (frontendu) se občas neobjeví kvůli cachování v prohlížeči (pamatuje si nějakou dobu starší verzi, aby načítal stránky rychleji). Načtení aktuální stránky jde vynutit pomocí Ctrl+Shift+R (na Macu Cmd+Shift+R). 


> toto issue tedy zavřu a vytvořím nové 
👍
