### ISSUE TITLE
Administrace - náhled na podřízené profily

### ISSUE THREAD

**Issue by PavlaOM** [cityvizor/cityvizor#590]
Potřeba upravit prostředí pro administraci tak, aby bylo snadno vidět všechny podprofily, které se vyskytují pod nadřazeným profilem.
Navazuje na #585

**Comment by PavlaOM** [comment]
@oroztocil můžeš tady pak doplnit konkrétní návrh, jak to co nejjednodušším způsobem udělat?

**Comment by prusovak2** [comment]
* pridat do seznamu profilu v administraci sloupec "nadrazeny profil" (parent) a filtrovani podle nej (full text search) https://beta.cityvizor.cz/admin/profily
* pridat do nastaveni profilu https://beta.cityvizor.cz/admin/profily/85/nastaveni k policku "Rodicovsky profil" proklik na rodicovsky profil (pokud ho dany profil ma nastaveny)
* pridat novou stranku do detailu profilu - tabulku podrazenych profilu

**Comment by PavlaOM** [comment]
@prusovak2 vypadá to dobře, díky Katko. Nasadíš na ostrou verzi?

**Comment by oroztocil** [comment]
Upraveno v release 5.6.0
