### ISSUE TITLE
přístup "profile manager" - problém s administrací

### ISSUE THREAD

**Issue by PavlaOM** [cityvizor/cityvizor#72]
Prosím o prověření nastavení administračních práv - pokud je profil ve stavu "připravujeme", nemá správce profilu s oprávněním profile-manager možnost administrace, protože po přihlášení do CV nemá vpravo dole nabídku "administrace" a tím pádem se nemůže na data ani podívat. Potřebovali jsme před zveřejněním ověřit správnost nahraných dat a musela jsem to obejít tím,že jsem dočasně změnila stav profilu na veřejný. Je možno to změnit?

**Comment by SmallhillCZ** [comment]
Bude vyřešeno migrací na CityVizor 4
