### ISSUE TITLE
chyba při kliknutí na detail výdajů z přehledu (chybná url)

### ISSUE THREAD

**Issue by DavidGregor-Net** [cityvizor/cityvizor#74]
Pokud jsem na přehledu (např. pro Praha 1) a kliknu na detail výdajů (např Školy), tak se nic nestane a do konzole se zaloguje error. Aplikace se chybně snaží dostat na URL /praha1/vydaje;rok=2019;skupina=31, ve které chybí klíčové slovo 'hospodareni'

Expected behavior: Aplikace by měla správně směřovat na výdaje s URL /praha1/**hospodareni**/vydaje;rok=2019;skupina=31

Reprodukováno v Google Chrome, Microsoft Edge i Mozilla Firefox. 

URL: https://cityvizor.praha.eu/praha1/prehled

![image](https://user-images.githubusercontent.com/52779234/66046981-32c88c80-e527-11e9-9c04-9bd9434373c5.png)

**Comment by SmallhillCZ** [comment]
Děkujeme, pokusíme se co nejrychleji opravit

**Comment by evapavlik** [comment]
@SmallhillCZ - řešil si tuto chybu nebo mám přenést do Trella k řešení?
