### ISSUE TITLE
Testy (backend)

### ISSUE THREAD

**Issue by SmallhillCZ** [cityvizor/cityvizor#77]
Pro backend nejsou vytvořeny jakékoliv testy.

**Comment by Adel770-gl** [comment]
@SmallhillCZ je to stále aktuální? Stále žádné testy?

**Comment by SmallhillCZ** [comment]
backendem je tady myšleno to, co je v adresáři server. a ano, stále žádné testy.

**Comment by kafkule** [comment]
@SmallhillCZ a nejedná se o duplicitu s nějakým z issues v rámci ostatních technical debts? 

Díky @Adel770-gl za kontrolu.

**Comment by evapavlik** [comment]
Ahoj, diky moc @kafkule a @Adel770-gl za prověření tohoto issue. V tomto případě není jednoduché určit priority, protože se jedná o technický dluh, který v rámci priorit produktového rozvoje řešíme.

Možná by @SmallhillCZ nám velmi pomohlo, pokud bys uměl říct rizika spojená s tím, že tyto testy nemáme a z Tvého pohledu - kdy je kritická doba, kdy je nutné je mít.

Pro hledání vývojáře s odpovídajícími kompetencemi by pomohlo doplnit zase odpovídající štítky - typ technologie, velikost atd, prosím @sitina @lukas-krecan.

Pro kontext, proč se obracím s prioritou na @SmallhillCZ - je to autor aplikace a bude tedy vědět nejlíp, jak hluboko ten technický dluh je.

**Comment by SmallhillCZ** [comment]
To není žádná konkrétní doba. Jde o to, že když nasadíme nějakou změnu a omylem tím rozbijeme třeba nahrávání dat obcí, tak se o tom dozvíme až od klientů. Když tam bude automatizovaný test, dozvíme se o tom automaticky už při založení pull requestu, protože GitHub to bude za nás automaticky testovat.

Myslím, že by to teď chtělo nasadit end to end testy na pár základních funkcionalit - přihlášení do administrace, nahrávání dat, základní zobrazení dat. Nemá teď podle mě smysl dělat unit testy na každý kousek kódu.

**Comment by Adel770-gl** [comment]
Ještě bych se vrátila ke komentáři od @evapavlik  "Pro hledání vývojáře s odpovídajícími kompetencemi by pomohlo doplnit zase odpovídající štítky - typ technologie, velikost atd, prosím @sitina @lukas-krecan mohli byste prosím uvést typ technologie?

**Comment by lukas-krecan** [comment]
Zavírám, je potřeba to udělat, ale nemá smysl to dělat jako samostatnou věc.
