### ISSUE TITLE
Testy (frontend)

### ISSUE THREAD

**Issue by SmallhillCZ** [cityvizor/cityvizor#79]
Implementace e2e testů

**Comment by Adel770-gl** [comment]
@SmallhillCZ jak budeme dále řešit tento technical debt?

**Comment by Adel770-gl** [comment]
@SmallhillCZ Máme přiřadit na někoho jiného? Pokud ano, i tak by bylo fajn vědět co a jak udělat abychom mohli začít pracovat na posunu. Díky moc!

**Comment by SmallhillCZ** [comment]
Ahoj, tohle je prostě od začátku z kategorie nice to have. Zatím se na tom neudělalo nikdy nic, takže není ani na co navazovat. 

Je to podobné, jak #77. Když nebudeme mít testy, nepoznáme, že něco při vývoji rozbijeme, dokud to nebude nefunkční na webu.

**Comment by lukas-krecan** [comment]
Zavírám, je potřeba to udělat, ale nemá smysl to dělat jako samostatnou věc.
