### ISSUE TITLE
Test import endpoint (backend)

### ISSUE THREAD

**Issue by SmallhillCZ** [cityvizor/cityvizor#81]
Neexistuje testovací API endpoint pro testování implementace nahrávání dat

**Comment by Adel770-gl** [comment]
@SmallhillCZ A co můžeme udělat proto abychom tento technical debt vyřešili? Co za blockery je třeba odstranit?

**Comment by SmallhillCZ** [comment]
Asi nejjednodušší je rozjet vedle testovací instanci. Blockery kromě času nejsou.

**Comment by Adel770-gl** [comment]
@SmallhillCZ takže potřebujeme na tohle najít dobrovolníka, nebo máš na to kapacitu?

**Comment by SmallhillCZ** [comment]
Já teď vůbec :(

**Comment by Adel770-gl** [comment]
@srdecny nebo @david-developer-play měl by někdo z vás na tuhle open issue prostor?

**Comment by smarek** [comment]
Vzhledem k aktuálnímu stavu řešení backend architektury, bude toto řešeno v rámci testovacího prostředí.
Pokud vyvíjím datové exporty pro CV, tak svou implementaci testuji proti testovacímu prostředí, jakmile jsem hotov, zavedu obec do produkčního prostředí.
Takže tento ticket není třeba řešit samostatně, bude řešeno v rámci #184 a např. #315 (nebo jiného budoucího PR pro řešení backend deploymentu)
