### ISSUE TITLE
Hlavicka podstranek - chybi CityVizor, matouci "zpet"

### ISSUE THREAD

**Issue by vojtechsvec** [cityvizor/cityvizor#82]
Na strance konkretni obce chybi v hlavicce cityvizor logo / nazev.

Problemy
- napr. kdyz prijdu z odkazu na konkretni obec, nevidim poradne, ze jsem na CV (obecne slaby branding)
- tlacitko zpet je v nelogicke a nestandardni pozici, navic neni jasne odkud kam zpet a chybi klasicka navigace "domu" pres logo (nemluve o tom, ze "< ZPET" je vizualne nejvyraznejsi prvek)

Navrh (MVP) reseni
- zbavit se "< ZPET"
- pridat nazev nebo soucasne logo (nez bude nove, klidne bych dal jen text), ktere bude odkaz na domovskou stranku

![image](https://user-images.githubusercontent.com/7902647/67964639-e1ccb680-fc00-11e9-889d-103cf6e13a8d.png)

**Comment by evapavlik** [comment]
Je řešeno v Trello: https://trello.com/c/b8Jt7fN3

**Comment by martinwenisch** [comment]
- [ ]  Upravit hlavicku CityVizoru podle navrhu ve Figme

<doplnit: odkaz na Figma design>

**Comment by evapavlik** [comment]
@martinwenisch dopln velikost ukolu

**Comment by Adel770-gl** [comment]
@evapavlik můžeme to tady považovat za vyřešené? Nebo je třeba zapracovat více požadavků?

**Comment by evapavlik** [comment]
Ahooj, moc díky, že sis @vojtechsvec našel čas na zpracování a @Adel770-gl za revizi tohoto issue. Pokud je to ve stavu labelu Ready to develop, je to tedy issue teprve připravené ke zpracování. Nevidím nikde issue vyřešené nebo k němu přiřazený pull request, je správně ho ponechat. Vyřešené bude ve chvíli, kdy k němu bude vyvinuté.

Cc @kafkule
