### ISSUE TITLE
subentity - hospodaření příspěvkových organizací

### ISSUE THREAD

**Issue by jpirko** [cityvizor/cityvizor#83]
Příspěvkové organizace mají separé účetnictví a často i jiný účetní SW. Bylo by fajn mít možnost je vést jako subentity města.

**Comment by evapavlik** [comment]
Hezký den Jiří, díky moc za podnět funkčnosti. Nyní předávám tento požadavek do Trella pro analýzu tohoto požadavku a zároveň prosím o předání Vašeho kontaktu pro další upřesnění požadavku, které budeme potřebovat. https://trello.com/b/BLVVohUU/cityvizor-requirements-board

Příjemný den,
Eva Pavlíková

**Comment by jpirko** [comment]
> Hezký den Jiří, díky moc za podnět funkčnosti. Nyní předávám tento požadavek do Trella pro analýzu tohoto požadavku a zároveň prosím o předání Vašeho kontaktu pro další upřesnění požadavku, které budeme potřebovat. https://trello.com/b/BLVVohUU/cityvizor-requirements-board
> 
> Příjemný den,
> Eva Pavlíková

jiri@pirko.cz

**Comment by Adel770-gl** [comment]
@evapavlik potřebujeme mít tohle stále jako open issues když odkazujeme dále na Trello, tudíž řešení se předpokládám bude dále řešit v Trellu?

**Comment by evapavlik** [comment]
@Adel770-gl Díky moc za upozornění a s omluvou za zpoždění. Podle historie v Trello kartiččce vidím, že je tento požadavek již zadaný v Productboardu, je možné jej tedy uzavřít.
