### ISSUE TITLE
Nacitani dat z jine instance

### ISSUE THREAD

**Issue by martinwenisch** [cityvizor/cityvizor#86]
Cilem je, aby instance CityVizoru byla schopna pres API exportovat a importovat sva data.

- [ ]  Specifikace rozhrani
Idealne 1 endpoint s exportovatelnymi daty (aka seznam jednotlivych dostupnych mest) a 1 endpoint exportujici(synchronizujici)/importujici instanci mesta.
- [ ]  Implementace na backendu
Tohle je idealni task pro serverless reseni, aby dlouho bezici task neblokoval zbytecne API instanci. Alternativne soucast API bezici napriklad pres noc. Castecne je potreba i datova analyza kolik dat se bude exportovat (v soucasnem stavu a v horizontu 1 roku pro cilovych 700 obci)

**Struktura dat:** 
SQL definice: https://github.com/cityvizor/cityvizor/tree/master/server/migrations
TS datove typy: https://github.com/cityvizor/cityvizor/tree/master/server/src/schema/database

**Poznamka:** Vyber technologie je soucast analyzy reseni, je mozne vytvorit export/import jako samostatnou komponentu v bezne pouzivanych technologiich.

**Comment by SmallhillCZ** [comment]
Exporty v podstatě jsou:
 - https://cityvizor.cz/api/exports/profiles `=> app.profiles`
 - https://cityvizor.cz/api/exports/profiles/{:id}/years `=> app.years`
 - https://cityvizor.cz/api/exports/profiles/{:id}/accounting/{:year} `=> data.accounting`
 - https://cityvizor.cz/api/exports/profiles/{:id}/events/{:year} `=> data.events`
 - https://cityvizor.cz/api/exports/profiles/{:id}/payments/{:year} `=> data.payments`

"Dokumentace": https://cityvizor.github.io/cityvizor/data/
Kód: https://github.com/cityvizor/cityvizor/blob/master/server/src/routers/exports/profiles.ts

**Potřeba je:**

- [ ] Přidat do `app.years` datum poslední změny (v současném kódu)
- [ ] Udělat importní skript, co to bude každou minutu kontrolovat a případně nahraje data

**Comment by HonzaV** [comment]
@SmallhillCZ  bavili jsme se s @martinwenisch, že by chtěl udělat exporty/importy na zelené louce bez využití stávajícího kódu (aspoň tak jsem to pochopil). Mám to +- připravené, jen musím doladit detaily.

**Comment by SmallhillCZ** [comment]
Okok, asi je to i lepší, že případné změny to nerozhodí. Ale stejně se bude
muset ve stávajícím kódu začít při importu ukládat poslední změna dat, aby
se poznalo, že jsou nová.

út 28. 1. 2020 v 17:14 odesílatel HonzaV <notifications@github.com> napsal:
