### ISSUE TITLE
Vyhledavani obci (cityvizor.cz)

### ISSUE THREAD

**Issue by martinwenisch** [cityvizor/cityvizor#87]
Na [cityvizor.cz](http://cityvizor.cz) bude vyhledavani zapojenych obci, potrebujeme:

- Na zaklade query vratit seznam zapojenych obci (s pripadnym typo?)
- Pokud vyhledavana obec neexistuje snazit se odhadnout realnou obec (nezapojenou do CityVizoru), aby mohl frotend nabidnout formular na zapojeni dane obce.

- Je mozne vratit celou DB (7000 obci) pro prazdnou query a nechat filtraci na frontendu, ale vzhledem k tomu, ze vysledek query budou jednotky obci vs 7000 obci cela DB prijde mi lepsi delat server query.

**Comment by zoul** [comment]
Tohle technicky souvisí s #91, v rámci kterého dáme dohromady data/službu se seznamem obcí, tak to pak můžeme recyklovat.
