### ISSUE TITLE
Pohled pres dodavatele (analyza)

### ISSUE THREAD

**Issue by martinwenisch** [cityvizor/cityvizor#88]
Analyza dat, ktera mame k dispozici (faktury, smlouvy), jejich prolinkovani do registru smuv a imformace, ktere dokazeme zjistit o plneni/dodavatelich.

Obecne co vse dokazeme zjistit z dostupnych faktur + smluv a pripadne zobrazit uzivatelum.

Jde o to vytvorit podklady pro Projektovy tym, jaka data jsme schopni zobrazit/parovat z dostupnych faktur a smluv.

Detaily: https://trello.com/c/IvKsVl3q

**Comment by joeythedataguy** [comment]
Working on this!

**Comment by vitekzkytek** [comment]
working on it

**Comment by Heulwen** [comment]
Also working :)

**Comment by martinwenisch** [comment]
Vystup:

https://www.figma.com/file/qAT1O04LYE1VX50OG3OF2v/CityVizor?node-id=0%3A1

https://docs.google.com/document/d/1ID1r7GLqfEY90ryD7JIufRmUiQG-zaroB8oj6ED7_2o/edit?usp=sharing
