### ISSUE TITLE
Dodavatelé, kterým obec dává z rozpočtu nejvíce peněz

### ISSUE THREAD

**Issue by martinwenisch** [cityvizor/cityvizor#89]
Je potreba vytvorit 2 stranky

- [ ]  Master ve stylu stranky Vydaje (s vybranou kapitolou) s prehledem nejvetsich dodavatelu (podle celkoveho objemu proplacenych penez, pres vsechny rozpoctove kapitoly)
- [ ]  Detail ve stylu stranky faktur s jednotlivymi fakturami daneho dodavatele.

**Comment by Adel770-gl** [comment]
@martinwenisch Máme k tomuto nějaký update? komu tuhle open issue přiřadíme?

**Comment by Adel770-gl** [comment]
Na základě chatu s @martinwenisch  přidávám komentář: issue je pripravena k vyvoji. Neni k tomu Avocode design, protoze sme se dohodli, ze neni potreba. Je to ve stejnem stylu jako vsechny ostatni tabulky master -> detail na CityVizoru. Data k tomu jsou.
Loni jsme na to nenasli Angular vyvojare (ale to jsme nenasli na nic), takze jestli je k dispozici Angular vyvojar, muze na tom zacit delat.
Pripadne by stalo za to prehodnotit, jestli je to jeste aktualni, to bude spise otazka na product ownera

- bude konzultováno ve slacku s PO

**Comment by PavlaOM** [comment]
určitě je to aktuální

**Comment by kafkule** [comment]
Vykopávám mezi #frontend na Slacku, zda by se nenašel Angular vývojář. Díky @PavlaOM za comment a @Adel770-gl za kontrolu nad issue.
