### ISSUE TITLE
Chybí licence zveřejněných dat

### ISSUE THREAD

**Issue by SmallhillCZ** [cityvizor/cityvizor#9]
_From @nesnera on February 12, 2019 18:51_

na stránkách [Data](https://otevrena-data-mfcr.github.io/CityVizor/data/) a asi též [O aplikaci](https://otevrena-data-mfcr.github.io/CityVizor/data/)

_Copied from original issue: otevrena-data-mfcr/CityVizor#145_

**Comment by evapavlik** [comment]
Požadavek byl založen do Trello boardu: https://trello.com/c/lowJye9h

**Comment by kafkule** [comment]
Evi @evapavlik a Martine @SmallhillCZ (případně Martin @martinwenisch), nemám přístup k nástěnce v Trellu, je možné doplnit nějaký update či nikoliv? Moc děkuji!

**Comment by SmallhillCZ** [comment]
My jsme to řešili když jsme to vyvíjeli na MF a podle nás se licence nemusí řešit, jelikož to [úřední](https://cs.wikipedia.org/wiki/%C3%9A%C5%99edn%C3%AD_d%C3%ADlo), nikoliv autorské dílo.

**Comment by Adel770-gl** [comment]
Tím pádem můžeme tuhle open issue považovat za uzavřenou? @evapavlik prosím o potvrzení

**Comment by evapavlik** [comment]
@SmallhillCZ Martinovi věřím, tak můžeme uzavřít. Díky moc všem za komentáře.
