### ISSUE TITLE
Poskytnout graf nebo jiné moduly CityVizoru obcím k publikaci na jejich vlastní portál

### ISSUE THREAD

**Issue by martinwenisch** [cityvizor/cityvizor#90]
User story:
Jako starosta chci mít možnost ukázat svým občanům na našem webu informace o tom, jak dobře obec hospodaří, aby občané věděli, že dobře hospodaříme a staráme se.

Jako finanční analytik chci mít možnost umístit veřejně naším občanům přehledné finanční výsledky ze CityVizoru, abych nemusel podobná data připravovat u nás a ušetřil čas.

Jako produktový manažer CityVizoru chci mít možnost nabídnout obcím možnost vložení našich grafů, aby ušetřili čas přípravou podobných grafů a zároveň aby vizuálně atraktivní podoba zaujala diváka a byl tím CityVizor propagován.

- [ ]  Vybrat vhodny graf/detail pro demo.
- [ ]  Rozhodnout format
Vyzkousel bych .svg generovane na backendu, pripadne udelal research podpory v prohlizecich, jestli je vhodnejsi .svg nebo .png nebo jiny format.
- [ ]  Nakodovat generator obrazku na backendu (lze pouzit kod z frontendu)
- [ ]  Spravne nastavit reverzni proxy, aby to prohlizece neblokovali

Co se spravneho nastaveni serveru (reverzni proxy) tyce, vystup by mel byt dokumentace/analyza nastaveni aby zobrazovani fungovalo spravne, ne nutne implementace (nginx, DNS ...)

**Poznamka:** Vyber technologie je soucast analyzy reseni, je mozne implementovat generator obrazku jako samostatne bezici komponentu v bezne pouzivanych technologiich.

**Comment by zoul** [comment]
Též bude potřeba nějak vhodně vyřešit UX – zamyslet se nad tím, co nejspíš bude uživatel potřebovat, a podle toho mu buď naservírovat jednu variantu, nebo dát na výběr. Takhle například vypadá dialog z datawrapper.de:

![export](https://user-images.githubusercontent.com/95329/69651351-3d5b5a00-1070-11ea-9577-091b3e617666.png)

**Comment by Horm** [comment]
Veškeré generování grafů pro frontend je ve složce [charts](https://github.com/cityvizor/cityvizor/tree/master/client/src/app/shared/charts). Komponenta bere data z API a převádí je na SVG.

**Comment by Horm** [comment]
Extrakce generování grafu do jedné komponenty (pro frontend i tento generátor) by asi připadala v úvahu. Muselo by se trochu dořešit zachování stylů a animací, ale to už je detail. 

Aby tedy pro jeden graf nebylo nutné mít několik HTTP požadavků, za mne připadá v úvahu jen sdílení "generátoru" ve formě kódu pro danou službu (obdobně jako NPM package). 

Tím se tedy dostáváme k technologiím. Knihovna pro generování SVG musí být volatelná TypeScriptem...

**Comment by Horm** [comment]
@martinwenisch a @zoul, omlouvám se za prodlevu. 

Pokud chceme zamezit duplicitním implementacím, vydal bych se směrem, že bych extrahoval pomocné funkce (JS) pro generování SVG z frontendu tak, aby byly použitelné i pro jednoduchý Express server. 

TS moc neznám a ani ho nemám moc v oblibě, takže samotný generátor bych psal v JS. (Nebo i ten Kotlin pokud neřešíme duplicitní implementace)

Budu rád za feedback.

**Comment by Horm** [comment]
Na callu jsme se rozhodli neřešit duplicitní implementace, tedy použijeme Kotlin (Ktor)

**Comment by jachym** [comment]
zvažte použití proj4js pro převod souřadnic - myslím, že tam i chybí korektní převod mezi ellipsoidy. viz https://github.com/cityvizor/cityvizor/commit/c5511e4f4f53b944006f70a0c3e56af6a66f6650

**Comment by Adel770-gl** [comment]
@HormCodes Vzhledem k poslednímu komentáři, znamená to že se tahle open issues může uzavřít?

**Comment by HormCodes** [comment]
@Adel770-gl, omlouvám se, zapomněl jsem nalinkovat pull request a status jsem napsal pouze k němu a ne tady. 

Pull request se zastavil na základě priorit, resp. redesignu hlavní stranky. Zda je tato funkce stále nutná a jaký je stav priorit nyní netuším. 

Pro dokončení by se hodila základní definice jaké SVG by se měla generovat a k nim příslušné designy jako šablony pro implementaci. 

Pull request je staršího data, bylo by nutné aktualizovat nad `master`

**Comment by Adel770-gl** [comment]
@HormCodes díky za odpověď a detail, v tuto chvíli počkáme na prioritizace od product ownera. Nicméně zkusím se zeptat @SmallhillCZ nevíš jakou má tahle open issue nalinkovaná na pull request prioritu?

**Comment by SmallhillCZ** [comment]
To je na OM/OICT, tj. Pavlu Kadlecovou/Martina Šebka...?

**Comment by Adel770-gl** [comment]
Feedback od Pavly: priorita v tuto chvíli není nijak vysoká. Je to jeden z těch úkolů v GitHubu, které bych přesunula do ProductBoardu a tam je doladila.

**Comment by Adel770-gl** [comment]
V případě, že máme open issue dále v řešení v ProductBoardu, můžeme v GitHubu uzavřít? Díky @evapavlik

**Comment by evapavlik** [comment]
@Adel770-gl Adel, ano, přesně tak, díky,.🙏

**Comment by Adel770-gl** [comment]
@evapavlik dle stávajícího stavu Product Boardu mi není jasné zda to tam je/ nebo není, ověřím ještě s Pavlou

**Comment by kafkule** [comment]
vložila jsem do PB, najdete pod https://cesko-digital.productboard.com/feature-board/1138166-feature-organization/features/5449318/ (cc @evapavlik @Adel770-gl), uzavírám

**Comment by PavlaOM** [comment]
@kafkule @Adel770-gl , díky, vyřešily jste i beze mne 👍
