### ISSUE TITLE
Cookies policy

### ISSUE THREAD

**Issue by martinwenisch** [cityvizor/cityvizor#92]
Je potreba analyza privacy policies podle 3rd party nalinkovanych ve frontendu (pouze Google analytics?). Zjistit jestli je pro ne potreba upozornit uzivatele na cookies, pripadne jestli to zle upravit, aby to potreba nebylo (u GA v pripade, ze nejsou pouzite na marketing).

Preference je nezobrazovat cookies hlasku uzivatelum, tedy pokud mozno uprava tak, aby to nebylo potreba.

V pripade, ze to bude nutne, navrhnout a implementovat cookie upozorneni.

**Comment by evapavlik** [comment]
Je to duplicitní k požadavku v Trello https://trello.com/c/7lp1i2jc, které zatím nemá analýzu. Uzavírám. Pokud bude nutné požadavek realizovat, zadáme jako nové issue.
